import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['cost-definition', 'Separate build cost from operating cost'], ['scope-drivers', 'Understand the scope drivers'], ['cost-worked-example', 'Compare two scopes for the same systems'], ['quote-brief', 'Prepare a quote-ready brief'], ['estimate-structure', 'Ask for a traceable estimate'], ['proposal-comparison', 'Compare proposals fairly'], ['scope-control', 'Control uncertainty and changes'], ['cost-reduction', 'Reduce cost without removing correctness'], ['quote-questions', 'Questions before requesting a quote'], ['cost-faq', 'Common questions']] as const;

export function ApiIntegrationCost() {
  return <ArticleGuide slug="api-integration-project-cost" category="Project planning" minutes={10} contents={contents} deck="An integration quote should price the agreed workflow, failure behavior, testing, and handover. Endpoint count alone cannot describe that work." coverCaption="NMIT’s estimation starts from data, recovery, and operating requirements. This scope-and-quote illustration contains no rates, price promise, or customer estimate." enquiry={{title:'Bring a workflow brief, get a scoped discussion.',text:'Share the systems, entities, direction, freshness needs, and acceptance criteria with NMIT. Agree discovery work and unresolved dependencies before treating an estimate as a delivery commitment.',href:'/contact/api',label:'Discuss integration scope'}}>
    <div className="article-introduction"><p>API integration project cost depends on the business scope, source-system behavior, data quality, recovery requirements, testing, and production ownership. Two projects connecting the same applications can require very different work.</p><p>A useful quote states what will be delivered, what is excluded, which assumptions remain unverified, and how acceptance will be measured. It separates implementation effort from recurring infrastructure, licensing, and support costs.</p><p>This guide explains the scope drivers and questions to answer before requesting a quote. It does not publish NMIT rates or an industry price range: no approved rate card, customer estimate, or workload measurements were supplied. The comparison examples below are hypothetical, intended to make proposals easier to assess.</p></div>

    <Section id="cost-definition" title="Separate delivery cost, operating cost, and change cost">
      <p>Delivery work includes discovery, contracts, implementation, environments, validation, release, documentation, and handover. Recurring costs include compute, data transfer, storage, software licensing, monitoring, support coverage, and ongoing recovery work.</p><p>Changes after the agreed scope are another category: a new entity, different source authority, additional partner, higher freshness objective, or new retention requirement can change both build effort and monthly operations. Keep these changes visible instead of burying them in a generic contingency line.</p><p><Source href="https://learn.microsoft.com/en-us/azure/well-architected/cost-optimization/cost-model">Microsoft’s cost-model guidance</Source> includes initial costs, run rates, and ongoing expenses. The <Source href="https://www.finops.org/framework/capabilities/planning-estimating/">FinOps Foundation’s planning and estimating capability</Source> emphasizes defining scope, modeling parameters, and comparing scenarios. These frameworks guide workload estimation; neither is a price list for custom integration services.</p>
      <Note title="An infrastructure calculator prices modeled resources">It does not automatically include discovery, field-mapping decisions, partner approval, failure tests, business acceptance, or an operating team. Ask which of these appear in the project quote.</Note>
    </Section>

    <Section id="scope-drivers" title="Identify the work behind each connection">
      <p>Count workflows and operations, not just application logos. Creating an order, updating its customer details, capturing a payment, issuing a refund, and reconciling results are distinct responsibilities even when they share an API base URL.</p>
      <Table caption="Scope drivers to document before estimating implementation effort" headings={['Driver', 'Lower-uncertainty scope', 'Work that can expand scope']} rows={[
        ['Business operations', 'One named flow and clear acceptance outcome', 'Multiple operations, approvals, exceptions, and partner variations'],
        ['Interface readiness', 'Supported contract and accessible test environment', 'Undocumented behavior, incompatible versions, or access delays'],
        ['Data mapping', 'Agreed identity, field owner, types, and validation', 'Duplicates, historic cleanup, ambiguous matching, and conflicts'],
        ['Freshness and capacity', 'Accepted window and representative workload', 'Strict response needs, bursts, quotas, and backlog recovery'],
        ['Failure handling', 'Known outcome resolution and duplicate-safe operations', 'Ambiguous writes, replay controls, compensation, or manual review'],
        ['Security and environments', 'Agreed permissions and approved deployment path', 'New trust boundaries, network changes, or extra assurance reviews'],
        ['Testing and handover', 'Explicit cases, evidence, runbooks, and owners', 'Partner certification, migration rehearsal, and extended support'],
      ]} />
      <p><Source href="https://spec.openapis.org/oas/latest.html">OpenAPI</Source> can document HTTP interfaces; <Source href="https://www.asyncapi.com/docs/concepts/asyncapi-document">AsyncAPI</Source> describes message interfaces. Contract files reduce some uncertainty, but they do not decide business identity, field authority, or correction ownership.</p><p>If legacy semantics need translation, an adapter becomes a deliberate work package. <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer">Microsoft’s anti-corruption-layer pattern</Source> explains that boundary. See <Link to="/blog/legacy-system-integration">our legacy integration guide</Link> for contracts and rollout, and <Link to="/blog/erp-crm-integration">our ERP–CRM guide</Link> for mapping and failed synchronization.</p><p>Discovery should also identify work owned by the buyer: access approvals, sample data, business decisions, source corrections, and partner contacts. Those dependencies affect elapsed time even when they are not supplier engineering hours.</p>
    </Section>

    <Section id="cost-worked-example" title="Worked comparison: the same ERP and CRM, two different projects">
      <p>Imagine a fictional business asking to “connect ERP and CRM.” That description could mean either of the following scopes. No currency or effort figures are assigned because the required evidence and supplier rates are not known.</p>
      <Table caption="Application count is identical; delivery obligations differ" headings={['Requirement', 'Scope A: customer summary', 'Scope B: operational order flow']} rows={[
        ['Direction and entities', 'One-way approved account summaries', 'Customer references, orders, status, and financial display fields'],
        ['Freshness', 'An agreed scheduled update window', 'Current validation plus independently updated downstream views'],
        ['Identity', 'Existing reviewed account cross-reference', 'Unmatched identities, parent records, and controlled merges'],
        ['Recovery', 'Retained row outcomes and repeatable import', 'Unknown writes, duplicate effects, callbacks, and controlled replay'],
        ['Acceptance', 'Field accuracy, completeness, and scheduled recovery', 'Business sequence, access checks, fault cases, and reconciliation'],
        ['Handover', 'Job monitoring and data-exception owner', 'Operational runbooks, escalation, partner coordination, and release evidence'],
      ]} />
      <p>Scope A still needs validation, secure access, and reliable restart. Scope B adds more coordination and outcome-resolution obligations. A quote for A cannot be compared with a quote for B just because both list two connected systems.</p><p>Specify the required pattern using <Link to="/blog/api-vs-event-driven-vs-batch-integration">our API, event-driven, and batch comparison</Link>. A new broker adds consumer, retention, lag-monitoring, and replay responsibilities; a supported scheduled transfer can be sufficient when the business accepts its freshness.</p>
    </Section>

    <Section id="quote-brief" title="Create a brief that makes the delivery boundary reviewable">
      <p>Provide a small, concrete brief before asking for a fixed delivery commitment. Redact credentials and personal data. Share contracts and representative synthetic payloads, not unrestricted production access.</p>
      <ol><li><strong>Outcome:</strong> describe one complete business flow and the user or team that benefits.</li><li><strong>Systems:</strong> name products, versions, environments, supported interfaces, and accountable contacts.</li><li><strong>Operations:</strong> list entities, directions, creation/update/deletion rules, and field authority.</li><li><strong>Workload:</strong> provide measured normal and peak volumes, payload sizes, growth assumptions, and required freshness.</li><li><strong>Failure behavior:</strong> define unknown outcomes, duplicate effects, retries, exception owners, and replay permissions.</li><li><strong>Release:</strong> state deployment constraints, partner windows, backfill, cutover, and acceptance evidence.</li><li><strong>Operations:</strong> name the receiving team, support coverage, runbooks, retention, and correction responsibilities.</li><li><strong>Exclusions:</strong> record work such as historic data cleanup, new application features, or third-party fees that requires separate agreement.</li></ol>
      <p>For payment writes, <Source href="https://docs.stripe.com/api/idempotent_requests">Stripe’s idempotency reference</Source> shows why retention and payload semantics matter to recovery. That documentation governs Stripe; your chosen provider may differ. Our <Link to="/blog/partner-payment-apis">payment integration guide</Link> helps specify those questions without assuming a universal guarantee.</p>
      <ContentImage article="api-integration-project-cost" name="scope-boundary" alt="NMIT engineers review approved workflow cards inside an integration scope boundary and a separate proposed change request." caption="An agreed boundary makes a quote reviewable. Additional entities or behavior need an explicit impact decision, not an unrecorded extension of the original acceptance criteria." />
    </Section>

    <Section id="estimate-structure" title="Ask for work packages, assumptions, and operating scenarios">
      <p>A traceable estimate connects each work package to its deliverable and acceptance evidence. Ask for discovery, contracts, build, security/configuration, testing, release, and handover to be explained at a useful level. A list of coding tasks alone can omit the work needed to operate the result.</p><p>Separate estimated effort from calendar duration. Dependencies, approvals, partner availability, and buyer review can delay a project without adding an equal number of engineering hours. Identify both the person supplying a prerequisite and the date or event that unlocks the next package.</p><p>If uncertainty remains, ask for a conditional range, its assumptions, and what discovery would narrow it. Do not treat a single number as greater confidence just because it is more precise. Keep risk allowance distinct from known scope, with a review or drawdown process defined commercially.</p><p>For recurring resources, document the modeled workload, region, environments, retention, and selected service assumptions. <Source href="https://docs.aws.amazon.com/wellarchitected/latest/cost-optimization-pillar/cost_select_service_analyze_all.html">AWS cost guidance on analyzing all workload components</Source> includes complete-resource assessment. Do not present a small request-price calculation as total operating cost.</p><p>Use planning scenarios for expected demand, peak demand, and recovery after an outage. Add retries, retained exceptions, logs, backups, and test environments. Distinguish recurring supplier support from resources billed directly to the buyer, and record the period covered by the comparison.</p>
    </Section>

    <Section id="proposal-comparison" title="Compare proposals against the same acceptance criteria">
      <p>Normalize the scope before comparing commercial totals. Identify what each proposal assumes the buyer will provide and which recurring obligations it includes. A missing item is a question to resolve, not automatic evidence of an inadequate supplier.</p>
      <Table caption="Questions for an equivalent proposal comparison" headings={['Comparison item', 'Ask each supplier', 'Evidence to request']} rows={[
        ['Delivery boundary', 'Which operations, entities, and directions are included?', 'Named flows and exclusions'],
        ['Data correctness', 'Who resolves identity, field authority, and invalid records?', 'Mapping decisions and correction path'],
        ['Recovery', 'What happens after an unknown remote outcome or duplicate?', 'Failure cases and pass criteria'],
        ['Release and access', 'Who supplies environments and coordinates partners?', 'Prerequisites and ownership'],
        ['Handover', 'Who operates, monitors, and replays retained work?', 'Runbooks, training, and support scope'],
        ['Commercial assumptions', 'What costs recur or change with workload?', 'Dated estimate assumptions and billing responsibility'],
      ]} />
      <p>Use <Link to="/blog/payment-api-testing-checklist">our payment testing checklist</Link> to make failure-case acceptance concrete. <Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/reliability-test">Microsoft’s reliability-testing guidance</Source> also supports checking full-flow recovery rather than component success alone.</p>
      <ContentImage article="api-integration-project-cost" name="quote-comparison" alt="NMIT engineers compare proposal A and proposal B using one shared acceptance checklist and a visible exclusions note." caption="Compare like-for-like obligations. The illustration contains no rates or preferred supplier; NMIT’s scope discussion should make acceptance, exclusions, and operating responsibility explicit." />
    </Section>

    <Section id="scope-control" title="Resolve uncertainty through discovery and record changes">
      <p>A discovery package should produce decisions: confirmed interface capabilities, representative mapping, workload evidence, a recovery proposal, and an updated scope. Agree its outputs and exit conditions before commissioning it. An open-ended investigation without decisions can become another source of uncertainty.</p><p>When a requirement changes, record the changed outcome, affected contracts, test evidence, release impact, recurring-cost impact, and approval owner. Define what remains valid from the original acceptance criteria. Avoid using “small field change” as a substitute for checking downstream meaning.</p><p><Source href="https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/">OWASP’s object-level authorisation guidance</Source> illustrates why exposing one additional resource can require access-control work. Similarly, a <Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html">transactional outbox</Source> can introduce durable relay and consumer obligations; it is not merely another API call.</p><p>If deployment crosses a cloud boundary, use <Link to="/blog/hybrid-cloud-migration-checklist">our hybrid migration checklist</Link> to identify identity, routing, final synchronization, and cutover responsibilities before they arrive as unplanned release work.</p>
    </Section>

    <Section id="cost-reduction" title="Reduce avoidable scope while preserving the required outcome">
      <p>Start with one valuable flow and explicit field ownership. Reuse supported interfaces where they meet the requirement. Provide reviewed synthetic examples and accountable source-system contacts. Defer optional entities through an agreed roadmap rather than removing recovery invisibly.</p><p>Relax freshness only when the business accepts the consequence. A scheduled summary may replace unnecessary immediate polling; an order eligibility decision may still need an authoritative response. Do not treat every performance requirement as negotiable.</p><p>Include observability in the delivery plan. <Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry’s signals</Source> provide a vocabulary for investigation across boundaries. Monitoring retained work and exception age can reduce later recovery uncertainty, though savings must be measured rather than promised.</p><p>Discuss the architecture and receiving team through <Link to="/services">NMIT’s API integration, cloud, and DevOps services</Link>. The operating model is part of scope even when a different team supplies support.</p>
    </Section>

    <Section id="quote-questions" title="Questions to answer before asking for a quote">
      <ul className="article-checklist"><li>What business outcome completes the first delivery?</li><li>Which systems, versions, operations, entities, and directions are included?</li><li>Who owns identity and each shared field?</li><li>What measured demand and freshness requirements should be modeled?</li><li>How must unknown writes, duplicates, failed records, and outages be handled?</li><li>Who supplies access, synthetic data, partner approval, and acceptance review?</li><li>What backfill, migration, deployment, and handover work is included?</li><li>Which costs recur, which exclusions need separate agreement, and what narrows remaining uncertainty?</li></ul><p>Bring these answers to <Link to="/contact/api">NMIT’s API integration enquiry</Link>. If the interface or authority decisions are unclear, use an <Link to="/contact/workshop">integration workshop enquiry</Link> to discuss the discovery boundary first.</p>
    </Section>

    <Section id="cost-faq" title="Common questions about API integration project cost">
      <h3>Can cost be estimated from endpoint count?</h3><p>Endpoint count is one input. Business behavior, data quality, recovery, security, validation, and operating responsibility can change the effort substantially.</p>
      <h3>Is a fixed price always better?</h3><p>No single commercial model suits every uncertainty level. Compare the agreed scope, assumptions, change process, and acceptance evidence before choosing a model.</p>
      <h3>How can we get a more reliable quote?</h3><p>Provide a concrete workflow brief, supported contracts, representative workload evidence, and named owners. Use bounded discovery to resolve gaps before requesting a firm commitment.</p>
    </Section>
  </ArticleGuide>;
}
