import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['field-ownership', 'Assign field ownership'], ['identity-mapping', 'Match records safely'], ['mapping-contract', 'Write the mapping contract'], ['sync-frequency', 'Choose update frequency'], ['conflicting-records', 'Resolve conflicting updates'], ['failed-syncs', 'Recover failed syncs'], ['backfill-cutover', 'Backfill and cut over'], ['sync-operations', 'Own the running workflow'], ['erp-faq', 'Common questions']] as const;

export function ErpCrmIntegration() {
  return <ArticleGuide slug="erp-crm-integration" category="Business data" minutes={10} contents={contents} deck="Agree which system owns each field, how quickly updates must arrive, and who fixes the records that fail to synchronize." coverCaption="NMIT connects ERP and CRM records through agreed identity, mapping, and recovery rules. The shared key represents a matching rule, not an automatic merge or a specific vendor product.">
    <div className="article-introduction"><p>ERP–CRM integration exchanges selected data between enterprise resource planning and customer relationship management systems. It lets sales teams see approved operational information and lets finance or fulfilment receive validated customer and order details.</p><p>The implementation is rarely just a field-name translation. Two records can describe the same organisation with different identifiers, different addresses, and different update times. A failed synchronization can also leave a valid order missing from one application even though the other accepted it.</p><p>This guide covers data mapping, synchronization frequency, conflicting records, and error handling. Its example is a fictional account-to-order workflow. For integrating a larger landscape without replacing useful applications, see <Link to="/blog/legacy-system-integration">our legacy system integration guide</Link>.</p></div>

    <Section id="field-ownership" title="Assign authority by field, not just by application">
      <p>Write a field-ownership register before enabling bidirectional synchronization. “Both systems own the customer” leaves important questions unanswered: can a sales representative change a legal billing name, and can an ERP update overwrite the sales contact’s email?</p><p>A useful boundary is one authorised writer for each field in a given business state. Other systems may display or propose changes to that field. Ownership can change at a defined lifecycle transition, but the transition needs approval and a documented rule.</p>
      <Table caption="Proposed ownership for a fictional account workflow" headings={['Field', 'Authoritative source', 'Receiving-system rule']} rows={[
        ['Legal billing name / tax identifier', 'ERP, after finance validation', 'CRM displays approved values; changes become requests'],
        ['Account contact / relationship notes', 'CRM', 'ERP receives only contact data required for operations'],
        ['Credit limit / balance', 'ERP', 'CRM displays a timestamped, read-only view'],
        ['Opportunity stage', 'CRM', 'Do not map directly to invoice or payment status'],
        ['Accepted order status', 'ERP after order validation', 'CRM displays fulfilment status without editing it'],
      ]} />
      <p>Record the business owner as well as the application team. Finance approves billing-field rules; sales operations approves contact rules; integration engineering implements the contract. The exact division is organisation-specific.</p><p><Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer">Microsoft’s anti-corruption layer pattern</Source> describes translating between systems with different semantics. Use the boundary to preserve meanings instead of forcing the ERP’s entire data model into the CRM. Our <Link to="/services">API integration services</Link> start with these interfaces and responsibilities.</p>
      <ContentImage article="erp-crm-integration" name="field-ownership" alt="NMIT engineers assign ERP billing and credit fields and CRM contact and sales fields to separate owners within one shared account." caption="One shared customer identity does not give both systems authority over every field. NMIT’s mapping boundary preserves the agreed owner for each value." />
    </Section>

    <Section id="identity-mapping" title="Use stable keys to identify the same business entity">
      <p>A name, telephone number, or email address can change. Two employees can share a company domain, and two legal entities can have similar trading names. Avoid treating those values as sufficient evidence for an automatic company merge.</p><p>Maintain a cross-reference such as <code>ERP account 00482 ↔ CRM company 9017</code>. Include tenant, entity type, and source system in the key. Store whether the match was supplied by an authoritative process, approved manually, or inferred and still awaiting review.</p><p><Source href="https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-alternate-key-reference-record">Dataverse alternate keys</Source> offer an integration-friendly way to reference records. <Source href="https://developers.hubspot.com/docs/api-reference/legacy/crm/objects/contacts/guide">HubSpot’s contact API documentation</Source> distinguishes record identifiers and supported contact operations. These are product-specific examples; check the actual object and endpoint you use.</p><p>If two CRM records map to one ERP account, quarantine the collision. Let a data steward decide whether they are duplicates, separate contacts, or separate legal entities. Preserve historical identifiers when an approved merge occurs so older events and invoices still resolve correctly.</p>
      <Note title="A missing match is a visible state">Do not invent an ERP identifier to keep a sync green. An unmatched record needs a reason, an owner, and a next action. It may be waiting for legitimate finance approval.</Note>
    </Section>

    <Section id="mapping-contract" title="Specify transformations, missing values, and write behavior">
      <p>A mapping contract should be executable and reviewable. For every field, record the source, destination, type, transformation, requiredness, null handling, authority, and rejection reason. Keep sample records and expected results alongside the contract.</p>
      <Table caption="Illustrative mapping rules, not vendor schemas" headings={['Source → destination', 'Transformation', 'Failure rule']} rows={[
        ['CUST_NO → externalAccountId', 'String; preserve leading zeros and source scope', 'Missing key becomes an identity exception'],
        ['CREDIT_STATUS → creditStatus', 'Explicit lookup: approved, held, or unknown', 'Unknown code is quarantined, not assumed approved'],
        ['BILLING_COUNTRY → billingCountry', 'Validate against the agreed code list', 'Reject unsupported values with a correction request'],
        ['BALANCE_AMOUNT + CURRENCY → balance view', 'Preserve decimal precision and currency; show freshness', 'Reject invalid precision or missing currency'],
        ['CONTACT_EMAIL → operationalContact', 'Copy only under the agreed business and permission rules', 'Invalid format becomes a field exception'],
      ]} />
      <p>Distinguish “field not sent” from “explicitly clear this field.” A partial update should not blank fields that the sender did not own or provide. Define how your API, file format, and mapping language represent that difference.</p><p><Source href="https://spec.openapis.org/oas/latest.html">The OpenAPI specification</Source> can describe HTTP payloads and response contracts. Use that description with business validation tests; a syntactically valid string may still contain an invalid account reference.</p><p>Where supported, an upsert combines create-or-update behavior around a stable key. <Source href="https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-upsert-insert-update-record">Dataverse’s upsert reference</Source> explains its operation semantics and table-specific differences. An upsert does not settle who owns a field or make an unrelated side effect safe to repeat.</p>
    </Section>

    <Section id="sync-frequency" title="Choose frequency from the consequence of stale data">
      <p>Ask what the consuming team can tolerate before selecting events or a schedule. A credit decision before accepting an order may require a current authoritative check. A salesperson’s account summary may tolerate a timestamped cached value. A monthly historical export can usually wait for a scheduled window.</p><p>A proposed service objective might be “approved address changes appear within ten minutes during business hours.” That is an example to negotiate, not an industry benchmark. Include downtime, backlog recovery, peak volume, and downstream rate limits in the agreement.</p>
      <ul><li><strong>Request–response API:</strong> useful when a user needs a current answer before proceeding; dependency outages affect the immediate workflow.</li><li><strong>Events or change feeds:</strong> useful for incremental updates; plan for duplicates, gaps, delay, and supported retention.</li><li><strong>Scheduled delta synchronization:</strong> useful when moderate lag is acceptable; preserve a durable cursor and process all pages.</li><li><strong>Batch snapshots:</strong> useful for bulk comparison and history; define the snapshot boundary and its effect on live updates.</li></ul>
      <p><Source href="https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-change-tracking-synchronize-data-external-systems">Dataverse change tracking</Source> supports synchronizing changes with external systems under documented table and retention conditions. Do not assume an expired cursor can resume without recovery. Our <Link to="/blog/api-vs-event-driven-vs-batch-integration">API vs event-driven vs batch decision guide</Link> compares these options in more detail.</p><p>A changed-since timestamp poll needs special care around ties, clock differences, paging, and deletes. Where a reliable vendor cursor exists, prefer it. Otherwise use an overlap window, stable tie-breaking, deduplication, and a separate reconciliation process to detect missed records.</p>
    </Section>

    <Section id="conflicting-records" title="Resolve conflicts without silently choosing the newest timestamp">
      <p>Suppose a sales representative edits company 9017’s display name at 10:05, while finance approves account 00482’s billing name at 10:06. The timestamps do not prove the fields have the same meaning. Apply the finance-approved billing name to the billing view and retain the sales-owned display name separately.</p><p>For the same owned field, use source versions or supported conditional writes to detect a stale update. <Source href="https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/perform-conditional-operations-using-web-api">Dataverse conditional operations</Source> use ETags and preconditions to detect version conflicts. A rejected precondition should trigger a re-read and a decision, not an unconditional overwrite.</p><p>Do not compare version tokens from different systems as if they share a sequence. Track a source’s version in its own scope. If ordering cannot be established reliably, retrieve current authoritative state before applying a delayed notification.</p><p>For bidirectional flows, record the origin and version of changes so the receiving system’s write does not bounce endlessly back to the sender. Apply only meaningful field changes. Do not discard all integration-originated updates if that would also hide legitimate downstream business rules.</p><p>Payment status deserves a separate authority rule: a CRM edit must not manufacture a paid invoice. See <Link to="/blog/partner-payment-apis#reconciliation">payment reconciliation and financial-record ownership</Link> for that boundary.</p>
    </Section>

    <Section id="failed-syncs" title="Separate temporary failures from records that need correction">
      <p>A service outage, an invalid country code, a missing parent account, and a conflicting version need different recovery paths. Store the source ID, mapping version, attempt ID, classified failure, and last successful checkpoint. Operators should see the business record involved without reading raw personal data in logs.</p>
      <Table caption="A proposed failed-sync policy" headings={['Failure class', 'Recovery path', 'Owner']} rows={[
        ['Throttling / temporary outage', 'Bounded retry; honour server timing; preserve checkpoint', 'Integration operations'],
        ['Invalid mapping / required field', 'Quarantine until source data or mapping is corrected', 'Data steward and mapping owner'],
        ['Missing parent record', 'Resolve parent; retry dependent record with a limit', 'Integration operations and source owner'],
        ['Version conflict', 'Re-read; apply field authority or seek approval', 'Business field owner'],
        ['Unknown write outcome', 'Retrieve destination state before unsafe replay', 'Integration operations'],
      ]} />
      <p><Source href="https://learn.microsoft.com/en-us/power-apps/developer/data-platform/api-limits">Dataverse service-protection limits</Source> document throttling and Retry-After behavior. Coordinate worker concurrency and SDK retries so recovery does not overwhelm the target.</p><p><Source href="https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html">Amazon SQS dead-letter queues</Source> illustrate isolating messages that repeatedly fail. A quarantine store still needs an operator, retention rules, and a controlled replay procedure. Fix the underlying reason before returning the same record to processing.</p><p>Advance checkpoints only when outcomes are durably accounted for. Depending on the feed, that can mean a successful write or a durable exception ready for later recovery. A process that reports “completed” after dropping failed rows creates data loss disguised as progress.</p>
      <ContentImage article="erp-crm-integration" name="sync-exceptions" alt="NMIT engineers isolate a flagged ERP–CRM record for review while valid account records continue to the receiving system." caption="Isolate invalid records with their failure reason. Correct the cause and verify replay safety before reprocessing; temporary outages require a different recovery policy." />
    </Section>

    <Section id="backfill-cutover" title="Backfill without overwriting newer live updates">
      <p>Choose a snapshot or change-feed boundary, load historical records, and then catch up changes from that boundary. If the source cannot provide a consistent snapshot, document the limitation and use comparison passes to resolve gaps. Coordinate parent and child entities before importing dependent records.</p><p>Store source versions with imported records so an older backfill cannot overwrite a later live update. For event publishing you control, the <Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html">transactional outbox pattern</Source> connects a database change and its outgoing event record within one transaction. It does not fix a vendor feed you cannot change or remove the need for duplicate-safe consumers.</p><p>Pilot one entity type or account group. Compare key counts, sampled field values, unmatched identities, and exception ageing. Counts alone can match while the wrong records are linked. Test approved merges, deletions, explicit field clears, a stopped worker, and a restart from the checkpoint.</p><p>For dependencies across a cloud boundary, follow the <Link to="/blog/hybrid-cloud-migration-checklist">hybrid cloud migration checklist</Link> before scheduling cutover.</p><p>Rollback needs a write policy and an in-flight recovery plan. Disabling the connector will not undo changes already applied. The <Link to="/blog/legacy-system-integration#phased-rollout">phased legacy-integration rollout</Link> describes validation gates and the limits of reversing traffic.</p>
    </Section>

    <Section id="sync-operations" title="Name the teams that own freshness and correctness">
      <p>Monitor freshness lag, oldest unprocessed change, cursor age, failed records by class, and identity collisions. Distinguish the backlog caused by a dependency outage from the quarantine caused by invalid data. Track per-entity success instead of only a connector uptime percentage.</p><p><Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry signals</Source> provide a vocabulary for traces, metrics, and logs. Correlate an incoming source change with its transformation and destination write, while restricting payload visibility and avoiding personal data in metric labels.</p><p>Give each exception category a named team and a correction path. Agree who approves mapping changes, who handles after-hours outages, and who checks downstream business rules after a replay. Review contracts when either application changes schema or permissions.</p><p>The delivery is complete when the receiving team can explain a delayed update and recover a failed record. Discuss the initial scope through <Link to="/contact/api">NMIT’s API integration enquiry</Link>, then agree the operating handover with <Link to="/services">our integration and DevOps teams</Link>.</p>
    </Section>

    <Section id="erp-faq" title="Common questions about ERP–CRM integration">
      <h3>Should every customer field sync in both directions?</h3><p>No. Decide who owns each field and which changes the other application can propose. Unrestricted bidirectional writes create conflicts and feedback loops.</p>
      <h3>How often should ERP and CRM synchronize?</h3><p>Use the business consequence of stale data to set a freshness objective. A current credit check, a customer summary, and a historical export can require different patterns and schedules.</p>
      <h3>What should happen when one record fails?</h3><p>Persist its reason and recovery state. Retry temporary failures within bounds, quarantine invalid data, and resolve conflicts through the field owner. Do not discard the row to advance the job.</p>
    </Section>
  </ArticleGuide>;
}
