import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['migration-boundary', 'Define the workload and recovery goals'], ['dependency-inventory', 'Build the dependency register'], ['hybrid-connections', 'Validate identity, DNS, and network paths'], ['migration-waves', 'Choose migration waves'], ['data-transition', 'Plan the data and writer transition'], ['cutover-runbook', 'Rehearse the cutover runbook'], ['migration-gates', 'Approve or stop with evidence'], ['post-cutover', 'Operate the remaining hybrid estate'], ['migration-faq', 'Common questions']] as const;

export function HybridCloudMigration() {
  return <ArticleGuide slug="hybrid-cloud-migration-checklist" category="Cloud migration" minutes={10} contents={contents} deck="Map the connections that cross your cloud boundary, rehearse the write transition, and make cutover decisions from evidence." coverCaption="NMIT’s hybrid-cloud work includes the connections between retained and migrated systems. The bridge is a readiness metaphor, not a promise of uninterrupted service." enquiry={{title:'Plan the workload and its remaining connections.',text:'Bring the dependency register, recovery objectives, and proposed cutover window to NMIT. Agree the cloud foundation, integration boundaries, and operating handover.',href:'/contact/cloud',label:'Discuss a cloud migration'}}>
    <div className="article-introduction"><p>A hybrid cloud migration checklist should begin with dependencies, not the date you want to move servers. Identify what each workload calls, what calls it, which data remains authoritative, and which connections will cross the on-premises and cloud boundary after cutover.</p><p>Hybrid migration leaves some applications, identity services, databases, or partner interfaces in their existing environment while others move. The result must operate as one business workflow even though components now have different network paths and operating teams.</p><p>This guide provides a dependency register, readiness checks, and a cutover sequence to adapt. It is not a universal runbook. The examples are fictional; choose targets and procedures from your actual platform capabilities and business requirements. For applications you plan to retain, see <Link to="/blog/legacy-system-integration">our legacy system integration guide</Link>.</p></div>

    <Section id="migration-boundary" title="Agree the workload boundary and recovery objectives">
      <p>Name the business flow first: accepting an order, servicing a customer, or completing a billing run. Record the user groups, operating hours, peak periods, financial impact of interruption, and owner who can approve reduced service.</p><p>Set recovery time and recovery point objectives with the business. RTO concerns the acceptable recovery duration; RPO concerns the acceptable time window of data loss. A successful server restart does not establish recovery of the complete workflow. <Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/metrics">Microsoft’s reliability-target guidance</Source> connects these objectives to workload design and testing.</p><p>Describe what is moving, what is staying, and what changes during this wave. Avoid treating a network relocation, database engine change, and application rewrite as one invisible task. Each creates different compatibility and recovery questions.</p><p><Source href="https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/plan/migration-adoption-plan">Microsoft’s migration planning template</Source> includes workload ownership, dependencies, security, licensing, and target architecture. Use it as a source of planning categories rather than assuming that completing a template proves readiness.</p>
      <Note title="A migration window is an operating agreement">Include preparation, final synchronization, validation, a decision point, and time for recovery. The latest safe stop point must leave enough time for the rehearsed contingency before the business window expires.</Note>
    </Section>

    <Section id="dependency-inventory" title="Create a register for every dependency across the boundary">
      <p>Combine observed connections with configuration review and interviews. Network discovery finds active traffic; it can miss a monthly export, a rarely used recovery path, a certificate renewal, or a connection absent during the observation period.</p><p><Source href="https://learn.microsoft.com/en-us/azure/migrate/concepts-dependency-visualization?view=migrate">Azure Migrate’s dependency-analysis documentation</Source> describes capturing network connections and grouping dependent systems. Treat the map as evidence to verify, not a complete record of business meaning or scheduled behavior.</p>
      <Table caption="A practical dependency register for migration discovery" headings={['Field', 'Record', 'Why it affects cutover']} rows={[
        ['Business flow and owner', 'What uses the connection; accountable team', 'Determines impact and validation responsibility'],
        ['Source and destination', 'Host/service name, environment, direction, port/protocol', 'Defines the changed network path'],
        ['Identity and trust', 'Service account, certificate, token audience, permission scope', 'Access can fail despite network connectivity'],
        ['Data and timing', 'Entity, authoritative writer, cadence, peak volume, freshness', 'Defines consistency and scheduling constraints'],
        ['Failure behavior', 'Deadline, retry policy, unknown-write handling, fallback', 'Predicts the effect of a slow or unavailable boundary'],
        ['Discovery evidence', 'Observation period, configuration, owner confirmation, gaps', 'Separates verified paths from assumptions'],
        ['Migration action', 'Move together, retain connection, change contract, or retire', 'Turns discovery into a wave decision'],
      ]} />
      <p>Check inbound connections too: partner callbacks, scheduled imports, monitoring collectors, and administration paths. For every dependency marked obsolete, ask its business owner to confirm that no critical process still uses it. Keep unknown owners visible as unresolved discovery work.</p>
      <ContentImage article="hybrid-cloud-migration-checklist" name="dependency-boundaries" alt="NMIT engineers review an application dependency map connecting identity, data, and partner services across a hybrid-cloud boundary." caption="Discovery needs both connections and context. NMIT’s planning identifies which paths cross the boundary, what they mean, and who validates them before cutover." />
    </Section>

    <Section id="hybrid-connections" title="Validate identity, DNS, routing, and operations from the target environment">
      <p>Test the actual application path from the future runtime. A successful ping or administrator login does not prove that the service account can resolve its hostname, establish TLS, request a token, and access the required object.</p>
      <ul className="article-checklist"><li>Confirm hostname resolution in both directions, including private zones and forwarding behavior.</li><li>Review address-space overlap, routing, firewall policies, outbound addresses, and partner allowlists.</li><li>Validate TLS hostname checks, certificate trust chains, expiry, and renewal ownership.</li><li>Test service identities, token audiences, restricted permissions, and access to secret stores.</li><li>Check hybrid-link capacity, latency, timeouts, and behavior when the link is degraded.</li><li>Verify administrative access, monitoring, backup destinations, and restoration permissions.</li></ul>
      <p><Source href="https://learn.microsoft.com/en-us/azure/dns/private-resolver-hybrid-dns">Microsoft’s hybrid DNS guidance</Source> describes resolution between Azure private zones and on-premises domains. The required resolver design depends on your existing network; do not copy a sample without reviewing reachability and trust.</p><p><Source href="https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/">Azure landing-zone guidance</Source> covers foundations such as connectivity, governance, and identity. Resolve shared platform responsibilities before the workload team arrives at cutover.</p><p>Measure complete transactions across the proposed boundary. A chain of small synchronous calls can become noticeably slower after relocation. Consider approved contract changes using <Link to="/blog/api-vs-event-driven-vs-batch-integration">our API, event-driven, and batch comparison</Link>; changing the pattern also changes freshness, recovery, and operating scope.</p>
    </Section>

    <Section id="migration-waves" title="Group by dependency and risk, then choose a representative pilot">
      <p>Applications that share a database transaction or require frequent low-latency calls may need to move together. Others can remain connected through an explicitly tested hybrid interface. Grouping only by server count can split a business flow at its most sensitive boundary.</p><p><Source href="https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/plan/select-cloud-migration-strategy">Microsoft’s migration-strategy guidance</Source> distinguishes approaches such as rehosting, replatforming, refactoring, and retaining workloads. Record the chosen approach for each workload and the reason it fits this wave.</p><p>Select a pilot with real dependency variety but a manageable business impact. Exercise retained identity, a partner connection, representative data volumes, and the intended monitoring. A pilot with no cross-boundary calls provides little evidence for a heavily hybrid workload.</p><p>Publish prerequisites and completion conditions for each wave. Reserve time for platform changes, partner approval, and failed pilot findings. When ERP and CRM are separated during transition, use the authority and freshness rules in <Link to="/blog/erp-crm-integration">our ERP–CRM implementation guide</Link> rather than relying on network location to determine ownership.</p>
    </Section>

    <Section id="data-transition" title="Design final synchronization and one authoritative write path">
      <p>State how the target receives the initial dataset and every later source change. Distinguish snapshots, incremental feeds, replication, and application-level reconciliation. Determine whether the selected method supports your schema, deletes, transaction boundaries, and data types.</p><p><Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/migration-database-rehost-tools/dms.html">AWS guidance on database migration tools</Source> describes database-specific replication and change capture. Tool capability alone does not prove that the receiving application has a consistent usable dataset.</p><p>Before switching writes, define how old workers, scheduled jobs, and partner submissions are paused or fenced. Drain or account for in-flight work. Capture a final source boundary and verify the target has reached it. Checking “replication running” is weaker than checking whether the final required changes arrived.</p><p>Validate key identities, critical field values, integrity rules, and business totals where appropriate. Record rejected or unmatched data. The <Link to="/blog/erp-crm-integration#backfill-cutover">ERP–CRM backfill guide</Link> explains why older bulk data must not overwrite newer updates.</p><p>After the target accepts new writes, the source may be stale. Returning traffic to it requires a tested reconciliation or reverse-synchronization procedure, compatible schemas, and an explicit decision about target-side effects. Switching a DNS record back does not reverse payments, notifications, or ledger entries.</p>
      <ContentImage article="hybrid-cloud-migration-checklist" name="cutover-control" alt="NMIT engineers check a source-to-target cutover switch with one active writer token and an amber decision checkpoint." caption="This controlled transition represents write authority. NMIT’s runbook must account for in-flight work and new target writes; the illustration does not imply that switching back automatically restores consistency." />
    </Section>

    <Section id="cutover-runbook" title="Rehearse a runbook with checkpoints and stop conditions">
      <p><Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/best-practices-migration-cutover/pre-cutover-stage.html">AWS pre-cutover guidance</Source> includes dependencies, testing, task owners, timing, and rollback planning. Make your runbook executable: one task, one owner, one expected observation, and a decision if it fails.</p>
      <ol><li><strong>Confirm readiness:</strong> owners, access, backups, target capacity, partner changes, and the agreed business window are available.</li><li><strong>Control incoming work:</strong> apply the approved write pause, queue policy, or fencing mechanism. Account for jobs and callbacks already running.</li><li><strong>Complete synchronization:</strong> record the final boundary and verify required target data and exceptions.</li><li><strong>Switch the agreed paths:</strong> change routing or application configuration; confirm the intended writer and prevent the old environment from resuming writes.</li><li><strong>Validate business flows:</strong> test user access, partner interfaces, callbacks, reports, and guarded effects using approved validation procedures.</li><li><strong>Make the decision:</strong> continue, pause, recover, or use the rehearsed contingency based on recorded thresholds and remaining time.</li><li><strong>Handover:</strong> retain evidence, assign heightened monitoring, and record any temporary operating constraints.</li></ol>
      <p>Rehearse restoration and manual steps, not just deployment. <Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/disaster-recovery">Microsoft’s disaster-recovery guidance</Source> discusses recovery planning. Measure what the team can actually do with the permissions and people available during the intended window.</p><p>If the migrated workflow makes financial writes, borrow the controlled fault cases from <Link to="/blog/payment-api-testing-checklist">our payment API testing checklist</Link>. A relocation can expose the same unknown-outcome and duplicate-effect problems as an ordinary partner outage.</p>
    </Section>

    <Section id="migration-gates" title="Use observable evidence to approve or stop cutover">
      <Table caption="Example gate categories; set workload-specific thresholds before rehearsal" headings={['Gate', 'Required evidence', 'Decision owner']} rows={[
        ['Dependency readiness', 'Confirmed critical paths and owners; unresolved gaps assessed', 'Workload and platform leads'],
        ['Data readiness', 'Final boundary reached; integrity checks and exceptions reviewed', 'Data owner'],
        ['Functional readiness', 'Approved business flows and partner connections validated', 'Business/workload owner'],
        ['Operating readiness', 'Alerts, access, runbooks, and recovery tested', 'Operations lead'],
        ['Cutover continuation', 'Observed outcomes within agreed thresholds and remaining window', 'Named cutover authority'],
      ]} />
      <p>Define thresholds before the event, including what is a blocker and who can accept a limitation. Avoid inventing a universal acceptable error rate or lag. Keep timestamps and evidence references so teams can distinguish a planned constraint from an unexpected defect.</p><p>Include rehearsal and hybrid operating work in the estimate. <Link to="/blog/api-integration-project-cost">Our project-cost guide</Link> explains why environments, partner coordination, recovery, and handover can materially change scope.</p>
    </Section>

    <Section id="post-cutover" title="Monitor the business flow and retire the source deliberately">
      <p>Watch completion time, failed transactions, oldest queued work, remaining hybrid-link health, and unmatched data. <Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry signals</Source> can connect traces, metrics, and logs across boundaries; a healthy virtual machine is not enough to establish a healthy order journey.</p><p><Source href="https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/optimize-workloads-after-migration">Microsoft’s post-migration guidance</Source> includes remaining hybrid dependencies and ongoing optimization. Review performance and operating costs after representative traffic, including scheduled cycles missed during the initial observation window.</p><p>Retire source resources only after approved retention, recovery, licensing, and dependency checks. Remove old jobs and obsolete credentials through controlled ownership. Retain the migration evidence and unresolved exceptions. Use <Link to="/services">NMIT’s cloud and DevOps services</Link> to discuss operating responsibility, or bring the dependency register to a <Link to="/contact/workshop">migration-planning workshop enquiry</Link>.</p>
    </Section>

    <Section id="migration-faq" title="Common questions about hybrid cloud migration">
      <h3>Can dependency discovery find everything?</h3><p>No. Observed traffic needs configuration review and business-owner confirmation, particularly for infrequent jobs, inbound partner paths, and recovery procedures.</p>
      <h3>Does database replication make cutover safe?</h3><p>It supports a data-transfer strategy. You still need final-boundary checks, application integrity validation, in-flight accounting, and write authority.</p>
      <h3>Is rollback just moving traffic back?</h3><p>No. Once the target accepts writes, the source can be stale. Rehearse how to preserve or reconcile those changes before returning it to authority.</p>
    </Section>
  </ArticleGuide>;
}
