import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['handover-boundary','Agree the receiving responsibility'],['handover-documents','Assemble the documentation'],['handover-runbooks','Write and rehearse runbooks'],['handover-access','Verify access without sharing secrets'],['handover-ownership','Assign production ownership'],['handover-drill','Run a receiving-team recovery drill'],['handover-acceptance','Accept with evidence and exceptions'],['handover-maintenance','Maintain the operating record'],['handover-faq','Common questions']] as const;
export function IntegrationHandover() {
  return <ArticleGuide slug="integration-handover-checklist" category="Operating handover" minutes={9} contents={contents} deck="A working connector needs a receiving team that can investigate it, recover retained work, and explain who owns the result." coverCaption="NMIT’s handover includes operating responsibility as well as documentation. The binder exchange is an illustration of that boundary, not evidence of a named customer engagement." enquiry={{title:'Make production ownership part of delivery.',text:'Discuss the receiving team, support boundary, recovery procedures, and acceptance evidence with NMIT before the integration reaches production.',href:'/contact/devops',label:'Discuss the operating handover'}}>
    <div className="article-introduction"><p>An integration handover checklist should cover documentation, runbooks, access, monitoring, and production ownership. The receiving team must be able to explain a delayed record and recover it safely without relying on an undocumented conversation with the original developer.</p><p>A delivery can pass functional tests yet remain difficult to operate. A missing partner contact, inaccessible exception store, or replay script with unclear side effects can turn an ordinary failure into a prolonged incident.</p><p>This guide defines a handover package and a receiving-team drill to adapt. It is an illustrative operating design, not a claim that NMIT supplies a particular support schedule or service-level commitment. Agree commercial coverage and accountable people explicitly. Use <Link to="/blog/api-integration-monitoring">our integration monitoring guide</Link> alongside the recovery procedures below.</p></div>
    <Section id="handover-boundary" title="Agree exactly what the receiving team will own">
      <p>Name the integration, business flow, environments, and release being handed over. Identify whether the receiving team owns application support, infrastructure, partner coordination, data corrections, or some combination. A generic label such as IT support can hide gaps between those responsibilities.</p><p>State hours of coverage, escalation expectations, planned maintenance ownership, and how an incident transfers between teams. Record dependencies that remain with the supplier or partner. Do not infer round-the-clock coverage from the existence of an alert destination.</p><p><Source href="https://sre.google/workbook/on-call/">Google’s on-call workbook chapter</Source> discusses sustainable response and operational readiness. Its practices need adaptation to your team size and coverage model rather than being treated as a ready-made staffing commitment.</p><p>Confirm who owns each business field and correction. In <Link to="/blog/erp-crm-integration#field-ownership">ERP–CRM field ownership</Link>, finance and sales can have different authorities. Operations may restore delivery without being authorised to invent a billing value.</p>
    </Section>
    <Section id="handover-documents" title="Document the running system and its business contracts">
      <Table caption="A versioned integration handover package" headings={['Artifact','Required content','How the receiver verifies it']} rows={[
        ['Architecture and inventory','Sources, destinations, retained dependencies, environments, trust boundaries','Walk through an actual approved workflow'],
        ['Contracts and mapping','Versions, identifiers, field authority, validation, deletion/clear rules','Explain a representative synthetic record'],
        ['State and recovery model','Unknown outcomes, retries, deduplication, checkpoints, exception paths','Trace one fault from detection to resolution'],
        ['Release and configuration','Build/deploy procedure, safe change boundaries, configuration locations','Locate the deployed version and controlled release path'],
        ['Monitoring and objectives','Completion definition, freshness, alerts, evidence access','Investigate a simulated delayed operation'],
        ['Runbooks and contacts','Prerequisites, safe actions, stop conditions, escalation','Execute a receiving-team drill'],
        ['Acceptance and limitations','Test evidence, unresolved issues, owners, review dates','Approve or record a specific remaining exception'],
      ]} />
      <p><Source href="https://spec.openapis.org/oas/latest.html">OpenAPI</Source> and <Source href="https://www.asyncapi.com/docs/concepts/asyncapi-document">AsyncAPI</Source> document interface structure. Include business meaning beside the contract: the authority behind an available balance, the source version behind a customer address, and the payment stage required for fulfilment.</p><p>Document scheduled work and infrequent connections. The <Link to="/blog/hybrid-cloud-migration-checklist#dependency-inventory">hybrid migration dependency register</Link> is useful even when no migration is planned. Record the observation period and known gaps so a diagram does not imply complete discovery.</p><p>Keep examples synthetic and redact sensitive payloads. Store documents in an accessible controlled location with a named maintainer. A link to a former engineer’s private workspace is not a durable handover artifact.</p>
    </Section>
    <Section id="handover-runbooks" title="Separate known procedures from investigation playbooks">
      <p>A runbook describes a defined procedure such as restarting an approved worker or replaying a reviewed record. A playbook supports investigation when the failure is not yet understood. <Source href="https://docs.aws.amazon.com/wellarchitected/latest/operational-excellence-pillar/ops_ready_to_support_use_runbooks.html">AWS runbook guidance</Source> and <Source href="https://docs.aws.amazon.com/wellarchitected/latest/operational-excellence-pillar/ops_ready_to_support_use_playbooks.html">AWS playbook guidance</Source> describe these complementary operating tools.</p>
      <ol><li><strong>Trigger:</strong> the symptom or alert that makes the procedure relevant.</li><li><strong>Prerequisites:</strong> environment, permissions, references, and dependency status to verify.</li><li><strong>Diagnosis:</strong> evidence to inspect before selecting a recovery action.</li><li><strong>Safe actions:</strong> the supported sequence, expected observations, and guarded effects.</li><li><strong>Stop conditions:</strong> uncertainty, conflicting evidence, access gaps, or side effects requiring approval.</li><li><strong>Verification:</strong> how to establish the intended business outcome after the action.</li><li><strong>Escalation:</strong> the accountable team and information to supply securely.</li></ol>
      <p>Do not write “retry the transaction” without defining which operation, which key, and what makes replay safe. Use the unknown-outcome handling in <Link to="/blog/partner-payment-apis#timeout-example">our payment integration worked example</Link>. A destination lookup or partner investigation may be the correct next step.</p><p>Include bounded rollback and fix-forward procedures where applicable. A database restore or routing reversal can affect work completed after the earlier checkpoint. Record those limits instead of describing recovery as one reversible command.</p>
      <ContentImage article="integration-handover-checklist" name="runbook-drill" alt="NMIT engineers consult a recovery runbook and restricted-access checklist before handling a stopped workflow and retained review ticket." caption="A runbook needs safe prerequisites, stop conditions, and outcome verification. NMIT’s handover should let the receiving team practise the procedure before it is needed during an incident." />
    </Section>
    <Section id="handover-access" title="Verify permissions without embedding credentials in documentation">
      <p>Record where credentials are managed, which roles use them, and who rotates or revokes access. Share references to approved secret stores, not passwords or signing keys. Verify that the receiving identity can perform its authorised tasks in the intended environment.</p><p>Separate read-only investigation, controlled replay, deployment, and financial correction permissions. Knowing a resource ID is not sufficient access. <Source href="https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/">OWASP’s object-level authorisation guidance</Source> is relevant to operator tools and customer endpoints alike.</p><p>Test restricted access and escalation for exceptional privileges. Record certificate renewal, partner allowlist, and service-account ownership. Include the route for emergency access and its audit requirements without weakening normal controls.</p><p>Confirm that access survives staff changes. Use approved team-owned repositories and operating resources. A successful demonstration through the supplier’s account does not prove the receiving team can respond independently.</p>
    </Section>
    <Section id="handover-ownership" title="Assign a person or team to each operating decision">
      <Table caption="Ownership categories to fill with accountable names before acceptance" headings={['Decision','Accountable role','Required boundary']} rows={[
        ['Workflow correctness','Business owner','Completion definition and permitted exceptions'],
        ['Source data correction','Data/field owner','Authority to correct or approve conflicting records'],
        ['Service recovery','Integration operations','Investigation, bounded retries, controlled replay'],
        ['Platform health','Platform team','Runtime, network, identity, backups and capacity'],
        ['Partner dependency','Partner coordinator','External incident route and endpoint contract'],
        ['Release/configuration','Application owner','Review, deployment, rollback limits and evidence'],
      ]} />
      <p>One role can cover several categories, but write down the responsibilities explicitly. Test the escalation path when the first responder is unavailable. If a partner has its own support schedule, record the resulting operating constraint.</p><p><Source href="https://learn.microsoft.com/en-us/azure/well-architected/operational-excellence/incident-response">Microsoft’s incident-management guidance</Source> supports defined roles and response processes. <Source href="https://sre.google/workbook/incident-response/">Google’s incident-response chapter</Source> provides further guidance on coordinated incidents. Adapt communication and command roles to the severity and team structure.</p>
      <ContentImage article="integration-handover-checklist" name="ownership" alt="NMIT engineers assign business, operations, and partner responsibility around one workflow and its correction note." caption="Technical recovery, business correction, and partner escalation can have different owners. The handover should make those boundaries visible before a failure crosses them." />
    </Section>
    <Section id="handover-drill" title="Worked drill: the receiving team investigates a retained order">
      <p>In an approved isolated environment, create a fictional order that was accepted locally but lacks confirmed destination completion. Retain its operation ID, source version, and attempt history. The receiving team leads; the delivery team observes and records gaps.</p><ol><li>The monitoring rule detects overdue retained work and sends the expected notification.</li><li>The responder locates the deployed version, operation record, and redacted correlated evidence.</li><li>The responder distinguishes a missing parent record from an unknown destination write.</li><li>The correct business or partner owner is contacted through the documented route.</li><li>An approved correction or safe resolution is applied with a recorded decision.</li><li>The team confirms destination evidence, guarded local effects, and exception closure.</li><li>The drill records documentation, permissions, timing, and escalation gaps for correction.</li></ol>
      <p>Measure the complete procedure, including detection and access. <Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/reliability-test">Microsoft’s reliability-testing guidance</Source> covers manual recovery and end-to-end validation. Compare observations with your agreed targets; this guide assigns no universal response-time promise.</p><p>Add provider-specific cases using <Link to="/blog/payment-api-testing-checklist">our payment testing checklist</Link>. Track what was simulated, what was verified against a provider contract, and what remains untested.</p>
    </Section>
    <Section id="handover-acceptance" title="Accept the operating boundary with evidence and recorded exceptions">
      <ul className="article-checklist"><li>The package matches the deployed version and contract.</li><li>The receiving team can locate records and investigate a delayed workflow.</li><li>Permissions, alert routing, escalation, and guarded recovery were exercised.</li><li>Each critical data field, exception category, and partner path has an accountable owner.</li><li>Release and rollback limits are understood, including new writes and external side effects.</li><li>Unresolved limitations have impact, owners, decisions, and review dates.</li><li>Coverage, ongoing maintenance, and supplier obligations are explicitly agreed.</li></ul>
      <p><Source href="https://sre.google/workbook/engagement-model/">Google’s SRE engagement model</Source> discusses readiness and operating collaboration. Acceptance should transfer the agreed responsibility, not simply mark documents delivered.</p><Note title="An exception needs an operating decision">A known limitation can be accepted only within an explicit responsibility and review process. Recording a gap does not automatically make it safe or assign its owner.</Note><p>Include drills, training, and post-release assistance in the <Link to="/blog/api-integration-project-cost">integration project estimate</Link>. Agree who resolves remaining gaps before the delivery team leaves the engagement.</p>
    </Section>
    <Section id="handover-maintenance" title="Keep the handover record current after acceptance">
      <p>Review documentation when source schemas, permissions, partner contracts, routing, or support teams change. Tie runbook updates to release review. During <Link to="/blog/incremental-legacy-modernization">incremental modernization</Link>, retained and replacement routes can need different recovery procedures.</p><p><Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry’s signals overview</Source> helps describe diagnostic evidence consistently. Preserve the distinction between telemetry and authoritative operation state as instrumentation evolves.</p><p>Bring the intended receiving team into a discussion of <Link to="/services">NMIT’s DevOps and integration services</Link>. Use an <Link to="/contact/workshop">integration workshop enquiry</Link> to map the workflow and unresolved operating responsibility.</p>
    </Section>
    <Section id="handover-faq" title="Common questions about integration handover">
      <h3>Is architecture documentation enough?</h3><p>No. The receiving team also needs contracts, access, alert ownership, recovery procedures, test evidence, and an agreed support boundary.</p>
      <h3>Should credentials go into the runbook?</h3><p>No. Document the approved secret-store reference and access process. Verify permissions separately and keep secrets out of documents and test evidence.</p>
      <h3>What proves the handover works?</h3><p>A receiving-team drill provides direct evidence of investigation and recovery capability. Record its limitations and the agreed ongoing responsibility.</p>
    </Section>
  </ArticleGuide>;
}
