import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['monitor-outcomes','Define the business outcome'],['monitor-signals','Measure requests and workflows'],['monitor-latency','Separate response time from completion time'],['monitor-correlation','Connect traces to durable records'],['monitor-example','Investigate an accepted but incomplete order'],['monitor-alerts','Route actionable alerts'],['monitor-safety','Protect telemetry and test detection'],['monitor-handover','Keep the operating model current'],['monitor-faq','Common questions']] as const;
export function IntegrationMonitoring() {
  return <ArticleGuide slug="api-integration-monitoring" category="Production operations" minutes={9} contents={contents} deck="Measure whether the workflow completed, not just whether the connector answered. Connect errors and latency to delayed orders, stale records, and unresolved operations." coverCaption="NMIT’s monitoring design follows technical signals through to workflow outcomes. The inspection motif is conceptual; it depicts no live dashboard or customer measurements.">
    <div className="article-introduction"><p>API integration monitoring should track errors, latency, failed workflows, and business outcomes together. Request health helps locate a problem. Workflow evidence establishes whether a customer order, payment confirmation, or account update actually reached its intended result.</p><p>An endpoint can return success while downstream work remains delayed. A queue can be available while an invalid record blocks processing. A payment can be accepted remotely while the application still has an unknown outcome. Your monitoring needs to distinguish these conditions.</p><p>This guide develops a monitoring model for one hypothetical order journey. It offers design choices to validate, not deployed NMIT results. Begin with <Link to="/blog/api-vs-event-driven-vs-batch-integration">our integration-pattern comparison</Link> if the workflow mixes APIs, events, and scheduled transfers.</p></div>
    <Section id="monitor-outcomes" title="Define completion in business terms before choosing charts">
      <p>Name the operation and the evidence that completes it. An approved order might require a durable ERP reference; a CRM change might require the destination to apply the correct source version. Payment fulfilment might require a documented capture stage. Define these separately from request acceptance.</p><p>Agree the completion deadline and the allowed exception path with the business owner. Expose pending, confirmed, failed, and investigation states in a durable store. A log line saying submitted is not a substitute for a recoverable operation record.</p><p><Source href="https://sre.google/sre-book/monitoring-distributed-systems/">Google’s SRE monitoring chapter</Source> describes latency, traffic, errors, and saturation as core signals. Use them alongside a workflow-specific definition of success; technical availability alone does not establish data correctness.</p><p>Define which requests enter the business denominator. Exclude deliberate validation failures only if the objective explicitly does so. Record cancellations and superseded operations consistently. An ambiguous write must not disappear from the denominator merely because its response never arrived.</p>
      <ContentImage article="api-integration-monitoring" name="business-outcome" alt="NMIT engineers inspect an accepted order whose fulfilment parcel remains pending, separating API acceptance from business completion." caption="Acceptance and completion are distinct evidence. NMIT’s monitoring design follows the durable operation until its agreed result or exception path is accounted for." />
    </Section>
    <Section id="monitor-signals" title="Give each monitoring layer a question it can answer">
      <p>Make metric definitions reproducible. Record whether a completion measure groups operations by submission time or completion time, when pending work becomes overdue, and how later corrections affect the result. A changing denominator can make an improving chart hide an accumulating backlog. Keep pending age and unresolved operation counts visible beside the completion rate, and review a sample of durable records when the numbers disagree.</p>
      <Table caption="Signals to adapt to your contracts and operating requirements" headings={['Layer','Measure','Question answered']} rows={[
        ['Request','Traffic, classified errors, dependency response time, throttling','Is the interface reachable and behaving as expected?'],
        ['Processing','Backlog, oldest work age, retry volume, consumer progress','Is retained work moving or accumulating?'],
        ['Data','Rejected records, identity mismatches, applied source version','Did the receiving system apply the intended information?'],
        ['Business','Completion within deadline, pending age, guarded effects','Did the flow deliver its required result?'],
        ['Control','Last successful collection, missing telemetry, alert delivery','Can we trust the monitoring evidence?'],
      ]} />
      <p>Classify errors by meaning: authentication, invalid data, quota pressure, dependency outage, version conflict, and unknown remote outcome. An aggregate failure counter can hide a small number of high-impact financial exceptions.</p><p>Track exception age as well as count. A stable queue of ten unresolved operations can still be unhealthy if the same ten have remained there for days. See <Link to="/blog/partner-payment-apis">payment timeout and reconciliation handling</Link> and <Link to="/blog/erp-crm-integration#failed-syncs">ERP–CRM failed-sync recovery</Link> for the states behind those signals.</p><p><Source href="https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html">Amazon SQS dead-letter guidance</Source> describes isolating repeated failures. A dead-letter destination does not make those messages resolved; monitor assigned recovery work as part of the business flow.</p>
    </Section>
    <Section id="monitor-latency" title="Measure response latency and end-to-end completion separately">
      <p>Measure caller response time, dependency duration, queue delay, processing duration, and complete workflow time where each applies. Include failed and timed-out attempts in the appropriate measurement. A chart of only successful responses can look healthy during a severe outage.</p><p>Use latency distributions to expose slow tails. <Source href="https://prometheus.io/docs/practices/histograms/">Prometheus’s histogram and summary guidance</Source> explains their different aggregation properties. Choose buckets and objectives that match the business decision rather than copying a dashboard’s default thresholds.</p><p>A request–response path ends when the caller receives a result or reaches its deadline. An asynchronous operation can finish later. Document its start and terminal evidence so accepted work is not incorrectly recorded as instantly complete.</p><p>For synchronization, measure source-to-destination freshness, not only connector execution time. For batch work, monitor expected arrival, last completed source window, and completeness checks. The <Link to="/blog/erp-crm-integration#sync-frequency">ERP–CRM freshness guide</Link> explains why different fields can have different accepted delay.</p><p>Clock skew can distort cross-host timing. Use trace durations for instrumented spans and a documented timestamp policy for business transitions. Preserve uncertainty where source timestamps are unreliable.</p>
    </Section>
    <Section id="monitor-correlation" title="Link logs, traces, and metrics without making them the state store">
      <p><Source href="https://opentelemetry.io/docs/concepts/observability-primer/">OpenTelemetry’s observability primer</Source> explains telemetry’s diagnostic role. Link a business operation to its attempts, source record, destination reference, and guarded effect through durable identifiers.</p><p><Source href="https://opentelemetry.io/docs/concepts/context-propagation/">OpenTelemetry context propagation</Source> and the <Source href="https://www.w3.org/TR/trace-context/">W3C Trace Context standard</Source> describe trace correlation across boundaries. Trace identity is not business identity: retries can create multiple traces for one operation, and a sampled trace may be absent.</p><p>Keep a lookup from the operation record to relevant correlation references. For messages, preserve appropriate context through the documented transport mechanism; treat context arriving from another trust boundary as untrusted input.</p><p><Source href="https://prometheus.io/docs/practices/naming/">Prometheus label guidance</Source> warns against unbounded cardinality. Put order IDs, customer IDs, and emails in neither metric labels nor unrestricted telemetry. Use bounded dimensions such as operation class, environment, and classified outcome.</p>
      <ContentImage article="api-integration-monitoring" name="trace-investigation" alt="NMIT engineers correlate log, trace, and workflow evidence using a shared reference to investigate a slow integration boundary." caption="Correlated evidence helps locate the failure. The durable workflow record remains authoritative when traces are sampled or telemetry is unavailable." />
    </Section>
    <Section id="monitor-example" title="Worked investigation: accepted requests, two incomplete orders">
      <p>Imagine a fictional test cohort of 120 accepted orders. At its agreed evaluation deadline, 118 have confirmed ERP references and two remain pending. That is evidence of two incomplete outcomes for this cohort, even if all 120 submission requests returned HTTP acceptance.</p><ol><li>Verify cohort membership and deadline semantics. Later completion belongs to the retained history; it does not retroactively change whether the original deadline was met.</li><li>Find the two pending operation records, not merely the most recent request errors.</li><li>Check attempt history, source identity, destination evidence, and the oldest retained work.</li><li>Follow correlated telemetry to distinguish quota delay, invalid parent data, or an unknown write.</li><li>Assign the correct recovery path and owner. Resolve destination state before a potentially duplicating write.</li><li>Confirm the business outcome and record the correction or exception decision.</li></ol>
      <p>Use independent reconciliation to catch missing associations that telemetry cannot establish. A duplicate attempt is not another accepted order. The <Link to="/blog/payment-api-testing-checklist">payment API testing checklist</Link> provides fault scenarios to validate this monitoring model before release.</p><p>This example contains no benchmark or production claim. The actual deadline, cohort, and exception threshold must come from your business requirements and provider contracts.</p>
    </Section>
    <Section id="monitor-alerts" title="Page for urgent action and retain nonurgent work for review">
      <p>Every alert needs an affected outcome, a responder, a safe first action, and an escalation path. A notification without an owner is only another retained event. Decide what warrants immediate interruption and what can become an assigned ticket.</p><p><Source href="https://sre.google/workbook/alerting-on-slos/">Google’s SLO alerting chapter</Source> discusses error-budget-based approaches. Adapt objective windows to the actual workflow, particularly for low traffic or scheduled processes; do not copy request-rate formulas into a sparse monthly export without analysis.</p><p>Use age-based checks for unknown operations and missing batch windows where appropriate. Monitor the monitoring path: absent telemetry, a stalled exporter, or failed notification delivery must not appear as zero errors.</p><p>Link the alert to a <Link to="/blog/integration-handover-checklist">documented runbook and ownership record</Link>. Include redacted investigation references, dependency status, and a clear prohibition on unsafe replay if the remote result is unknown.</p>
    </Section>
    <Section id="monitor-safety" title="Restrict telemetry and test the complete detection path">
      <p>Limit payload capture and apply retention and access controls. <Source href="https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/">OWASP’s object-level authorisation guidance</Source> is relevant to investigation tools too: knowing a payment reference does not grant permission to view its data.</p><p>Inject a dependency timeout, invalid record, stuck consumer, stale source window, and telemetry interruption in an approved isolated environment. Verify signal collection, rule evaluation, notification, responder access, investigation, and outcome verification.</p><p><Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/reliability-test">Microsoft’s reliability-testing guidance</Source> supports checking end-to-end recovery. Retain which behaviors were simulated and which partner capabilities were verified. An alert-rule unit test cannot establish that a human receives the notification and can execute the runbook.</p>
    </Section>
    <Section id="monitor-handover" title="Keep monitoring aligned with contract and ownership changes">
      <p>Review objectives, labels, retention, and runbooks when entities, providers, or interfaces change. During <Link to="/blog/incremental-legacy-modernization">incremental legacy modernization</Link>, compare outcomes across the retained and replacement routes so a healthy new service cannot hide a failing old dependency.</p><p>Price instrumentation, evidence retention, and operating handover in the <Link to="/blog/api-integration-project-cost">integration project scope</Link>. Discuss the production boundary through <Link to="/services">NMIT’s integration and DevOps services</Link> or use an <Link to="/contact/workshop">architecture workshop enquiry</Link> to define one measurable flow.</p>
    </Section>
    <Section id="monitor-faq" title="Common questions about API integration monitoring">
      <h3>Are HTTP error rates enough?</h3><p>No. Accepted work can fail later. Add durable completion, pending age, correctness checks, and independent reconciliation where relevant.</p>
      <h3>Should every failure trigger a page?</h3><p>No. Route urgent actionable impact to the responder and retained nonurgent exceptions to accountable review. Base thresholds on agreed objectives.</p>
      <h3>Can distributed traces replace operation records?</h3><p>No. Traces diagnose attempts and timing. Durable operation records support recovery, business identity, and outcome accounting even when telemetry is sampled or missing.</p>
    </Section>
  </ArticleGuide>;
}
