import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['pattern-definitions', 'What the three choices mean'], ['pattern-decision-table', 'Compare the tradeoffs'], ['choose-api', 'When an API fits'], ['choose-events', 'When events fit'], ['choose-batch', 'When batch fits'], ['hybrid-example', 'A practical hybrid example'], ['ordering-recovery', 'Ordering and recovery'], ['operating-cost', 'Compare operating cost'], ['buyer-checklist', 'Questions before choosing'], ['patterns-faq', 'Common questions']] as const;

export function IntegrationPatterns() {
  return <ArticleGuide slug="api-vs-event-driven-vs-batch-integration" category="Architecture decisions" minutes={10} contents={contents} deck="Choose the connection from the workflow’s response needs, freshness limits, failure rules, and operating budget." coverCaption="NMIT selects integration patterns by business workflow: an immediate request, a published change, or a grouped transfer. These are conceptual motifs, not vendor guarantees or a complete message topology.">
    <div className="article-introduction"><p>API vs event-driven integration is a choice about how applications coordinate a workflow. A synchronous API asks another system for a result now. An event-driven flow publishes a change for consumers to process independently. Batch integration transfers a defined collection of records in a scheduled or bounded run.</p><p>Choose an API when a caller needs an authoritative result before continuing. Choose events when consumers can react independently and tolerate a measured delay. Choose batch when grouped transfer and processing windows fit the business requirement. A system can use all three for different steps.</p><p>This comparison focuses on latency, coupling, ordering, and operating cost. It is a decision framework, not a performance benchmark. If you are still deciding which existing applications to retain, start with <Link to="/blog/legacy-system-integration">NMIT’s legacy system integration guide</Link>.</p></div>

    <Section id="pattern-definitions" title="Define the choices before comparing them">
      <p>An API is an interface, not necessarily a synchronous architecture. An HTTP endpoint can accept work asynchronously; an event producer or batch loader can also use APIs. For this guide, “API integration” means synchronous request–response unless stated otherwise.</p><p>An event describes something that happened, such as an approved order changing state. A command asks a specific recipient to do something. Sending a payment command through a queue changes delivery mechanics; it does not make that command an established payment fact.</p><p><Source href="https://learn.microsoft.com/en-us/azure/architecture/guide/architecture-styles/event-driven">Microsoft’s event-driven architecture guide</Source> describes producers, channels, consumers, and the operating tradeoffs of asynchronous processing. The <Source href="https://docs.aws.amazon.com/batch/latest/userguide/what-is-batch.html">AWS Batch overview</Source> describes managed batch-job execution. A job service does not define your business dataset: distinguish incremental batches from complete snapshots in the integration contract.</p><p>Also distinguish an HTTP 202 acceptance from completion. The <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/asynchronous-request-reply">asynchronous request–reply pattern</Source> uses a way for callers to check progress after acceptance. If a vendor offers that flow, assess it as asynchronous work rather than assuming a successful initial response means the business task finished.</p>
    </Section>

    <Section id="pattern-decision-table" title="Decision table: latency, coupling, ordering, and cost">
      <p>Use the table to shortlist a pattern, then verify the actual endpoint, broker, dataset, and team capabilities. “Near real time” is not a contractual delay bound; a queue can accumulate hours of work during an outage.</p>
      <Table caption="Qualitative comparison; actual behavior depends on implementation" headings={['Decision factor', 'Synchronous API', 'Event-driven', 'Batch']} rows={[
        ['Latency / freshness', 'A result in the caller’s request window; bounded by dependencies', 'Often low delay, but backlog and consumers determine freshness', 'Schedule, transfer, and processing window determine freshness'],
        ['Coupling', 'Caller and dependency must coordinate availability and contract', 'Less runtime coupling; schema and meaning still shared', 'Shared file/schema, schedule, and completion agreement'],
        ['Ordering', 'Concurrent requests do not imply business order', 'Scope ordering by entity, partition, or message group', 'Define file/record order and precedence against live updates'],
        ['Failure recovery', 'Timeout can leave a write outcome unknown', 'Duplicate-safe processing, checkpoints, and controlled replay', 'Partial-run accounting, restart points, and duplicate-safe imports'],
        ['Operating cost', 'Request load, rate limits, availability, and request tracing', 'Broker, storage, retention, consumers, lag monitoring, and replay', 'Scheduled compute, data movement, validation, and exception handling'],
        ['Useful workflow', 'Current eligibility or order validation before proceeding', 'Distributing approved changes to independent consumers', 'Historical load, scheduled reporting, and bulk reconciliation'],
      ]} />
      <Note title="Compare requirements, not labels">A simple request–response flow may be the right choice. Adding a broker increases responsibilities as well as flexibility. Batch can be appropriate when the business accepts its processing window and the recovery plan is explicit.</Note>
    </Section>

    <Section id="choose-api" title="Choose a synchronous API for a result the caller needs now">
      <p>Use a request–response interaction for an authoritative check that must complete before a user proceeds: checking account eligibility, validating an order, or reserving an available resource. Define the response contract, permissions, deadlines, and what the caller shows when the dependency is unavailable.</p><p><Source href="https://spec.openapis.org/oas/latest.html">OpenAPI</Source> describes HTTP interfaces in a machine-readable contract. Verify business meaning alongside the schema: a field named available may refer to stock at a particular warehouse or a snapshot taken earlier.</p><p>A chain of calls can couple the user experience to several downstream systems. Measure the end-to-end path and test the slowest dependency. Caching can help read workflows when the application exposes freshness and the business accepts stale answers. It cannot make an unconfirmed payment safe to repeat.</p><p><Source href="https://www.rfc-editor.org/rfc/rfc9110.html#name-idempotent-methods">HTTP idempotent-method semantics</Source> describe protocol behavior. A business write still needs endpoint-specific duplicate prevention and recovery. Our <Link to="/blog/partner-payment-apis">payment API timeout and retry guide</Link> follows the consequences of a lost response.</p><p>Before approving the approach, ask whether a temporary failure should block the user, return a pending operation, or use an explicitly approved fallback. Record that decision in the contract and acceptance tests.</p>
    </Section>

    <Section id="choose-events" title="Choose events for independent reactions to an approved change">
      <p>Events suit workflows where one approved change feeds several applications, such as an order update that refreshes the CRM, an analytics view, and a customer notification. The producer should not need to wait for every consumer before completing its own local work.</p><p>Decoupling runtime availability does not remove shared meaning. Agree the event type, entity ID, source, schema version, occurrence time, and relevant business version. Avoid broadcasting personal or financial data to consumers that do not need it.</p><p><Source href="https://www.asyncapi.com/docs/concepts/asyncapi-document">AsyncAPI documents</Source> describe message interfaces and channels. Use that contract to communicate expected messages and security requirements, while defining retention, replay permission, and operating ownership separately.</p><p>When you control the source application, a <Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html">transactional outbox</Source> can persist a change and its outgoing event record together. The relay and consumer can still encounter retries, so guard downstream effects independently.</p><p>Set a freshness objective for each consumer rather than claiming every view is current immediately. A customer-facing screen may need to show “updating” or perform an authoritative read. The <Link to="/blog/erp-crm-integration#sync-frequency">ERP–CRM update-frequency guide</Link> gives examples of matching data freshness to the business consequence.</p>
    </Section>

    <Section id="choose-batch" title="Choose batch for grouped work with an accepted processing window">
      <p>Batch suits historical imports, scheduled exports, independent reconciliation, and partner interfaces that provide files rather than events. It can also reduce repeated API calls when a supported bulk interface is available. The business must accept the time between a change and the next completed run.</p><p>Define each dataset with a batch ID, schema version, record count, source window, timezone, and completeness indicator. Include a checksum or equivalent transport-integrity check where supported. Know whether the file is a snapshot, a delta, or an adjustment to an earlier delivery.</p><p>Plan for a file that arrives late, a run that succeeds on only half the rows, and a duplicate file sent after an uncertain acknowledgement. Persist per-record outcomes or safe chunks, and ensure a restarted job does not repeat business effects. An overall job exit code is insufficient when rejected rows disappear from view.</p><p>Specify the handling of a missing file separately from an empty but valid file. Check duplicates, invalid identities, and totals by relevant currency or business unit. Never treat a missing record in an incremental file as an instruction to delete it.</p><p>See <Link to="/blog/partner-payment-apis#reconciliation">payment reconciliation</Link> for how grouped external records can check an operational flow independently. See <Link to="/blog/erp-crm-integration#backfill-cutover">ERP–CRM backfill and cutover</Link> for keeping older bulk data from overwriting live changes.</p>
    </Section>

    <Section id="hybrid-example" title="Worked example: one order journey, three integration patterns">
      <p>Consider a fictional business taking a partner order against an ERP account. The following architecture is an option to test, not a deployed NMIT case study or a prescription for every business.</p>
      <ContentImage article="api-event-batch-integration" name="hybrid-order" alt="NMIT engineers coordinate one order using an API for an immediate check, an event for notification, and a batch of records for later comparison." caption="One order journey can use three patterns for different needs. NMIT’s design assigns a contract, recovery path, and owner to each boundary." />
      <ol><li><strong>Validate through an API:</strong> the order service asks the authoritative system whether the account is eligible. A dependency outage produces a clear pending or unavailable response rather than a fabricated approval.</li><li><strong>Record the accepted order:</strong> commit the local order and, where supported, an outgoing approved-order event record together. The event is a fact about that local commit, not proof that all applications have updated.</li><li><strong>Distribute through events:</strong> CRM and notification consumers process the approved change with separate duplicate guards. CRM delay does not require creating the original order again.</li><li><strong>Check through batch:</strong> an agreed comparison matches accepted orders with ERP records. It raises unmatched identities and incomplete downstream writes for investigation.</li></ol>
      <p>This design gives a buyer concrete questions: who owns the eligibility answer, what makes an order approved, how long can the CRM lag, and who resolves the comparison exceptions? <Link to="/services">NMIT’s API integration and cloud services</Link> provide the delivery context for those boundaries.</p>
    </Section>

    <Section id="ordering-recovery" title="Make ordering and duplicate handling explicit">
      <p>Sending messages in sequence does not guarantee that every consumer applies them in sequence. Concurrent workers, retries, and delayed older messages can change processing order. Choose the ordering scope from the business entity: updates for one order may need sequence, while unrelated orders can proceed independently.</p><p><Source href="https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues-at-least-once-delivery.html">Amazon SQS standard queues</Source> document at-least-once delivery. <Source href="https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues-understanding-logic.html">SQS FIFO processing</Source> describes ordering by message group. A broker’s duplicate or ordering feature does not guarantee that a remote database or payment endpoint performs exactly one business effect.</p><p>Store consumed event identity and the resulting local change atomically where possible. If processing calls another system, use that system’s safe operation mechanism or an explicit outcome-resolution process. Preserve the latest applied source version so an older event cannot silently regress an entity.</p><p>Distinguish work sharing from fan-out. The <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/competing-consumers">competing consumers pattern</Source> spreads work among workers; a publish–subscribe design sends changes to independent subscriber groups. Adding more workers to one group does not create a new independent business subscriber.</p><p>For repeated failures, use a controlled exception path such as the <Source href="https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html">SQS dead-letter queue mechanism</Source>. Investigate before replay, assess the impact on ordering, and decide whether an old message is still valid for the entity’s current state.</p>
      <ContentImage article="api-event-batch-integration" name="ordering-replay" alt="NMIT engineers check update 02 against the current order state and hold older update 01 for review, with duplicate update cards grouped aside." caption="Arrival order does not establish business order. Check source versions and guard duplicate effects before applying an update or replaying an older message." />
    </Section>

    <Section id="operating-cost" title="Estimate total operating cost, including recovery">
      <p>For a quote-ready brief and supplier comparison, see our <Link to="/blog/api-integration-project-cost">API integration project cost guide</Link>.</p><p>Do not compare only request pricing, broker charges, or the cost of one scheduled job. Include engineering, environment setup, data retention, monitoring, on-call time, reconciliation, and the business cost of delayed or incorrect records.</p><p>Build a workload model using expected records, peak rates, payload sizes, consumer count, retention days, and acceptable backlog recovery time. Add retry amplification, backfill traffic, and downstream quotas. These inputs should come from the business and measured prototypes rather than invented industry averages.</p><p>APIs require enough available capacity for the request window. Events add broker and consumer operations but let consumers absorb work independently. Batch can use bounded compute windows while creating deadlines around delivery and completion. None is always cheapest.</p><p><Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry’s signals</Source> can support tracing and monitoring across the chosen boundaries. Track end-to-end business completion and exception age, not just the health of the connector or queue.</p>
    </Section>

    <Section id="buyer-checklist" title="Ask these questions before approving an integration approach">
      <ul className="article-checklist"><li>Does the caller need a result immediately, or can it receive a pending operation?</li><li>What is the maximum accepted stale-data window for each consuming team?</li><li>Which application owns the decision and the fields involved?</li><li>What are the actual duplicate, ordering, retention, and replay guarantees?</li><li>How will a partial write or an unknown remote outcome be resolved?</li><li>Can the team operate the selected infrastructure and recover from a backlog?</li><li>Who approves corrections, schema changes, and the eventual handover?</li><li>What representative workload will validate latency, capacity, and operating cost?</li></ul><p>Record the answers in a one-workflow decision document. Compare the simplest viable option against alternatives, then pilot with failure scenarios. Use <Link to="/contact/workshop">NMIT’s integration workshop enquiry</Link> to discuss the interfaces and operating scope.</p>
    </Section>

    <Section id="patterns-faq" title="Common questions about integration patterns">
      <h3>Are events always faster than APIs?</h3><p>No. Events can remove a caller’s wait for downstream consumers, but business completion still depends on queue delay and processing. Measure the time to the outcome the user actually needs.</p>
      <h3>Is batch integration outdated?</h3><p>No. Batch is useful for accepted processing windows, historical transfers, and independent reconciliation. It needs explicit completeness, restart, and exception rules.</p>
      <h3>Can APIs, events, and batch be combined?</h3><p>Yes. A workflow can validate through an API, publish an approved change as an event, and compare external records through a scheduled batch. Each boundary needs a defined contract and owner.</p>
    </Section>
  </ArticleGuide>;
}
