import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['strangler-fit','Decide whether the pattern fits'],['strangler-slice','Choose a business capability'],['strangler-routing','Control the routing boundary'],['strangler-data','Assign data and write authority'],['strangler-example','Work through one replacement'],['strangler-release','Validate and release in stages'],['strangler-retire','Verify before retiring legacy code'],['strangler-operations','Budget the transition and handover'],['strangler-faq','Common questions']] as const;
export function LegacyModernization() {
  return <ArticleGuide slug="incremental-legacy-modernization" category="Legacy modernization" minutes={9} contents={contents} deck="Replace one business capability behind a controlled boundary. Keep retained functions operating while you validate data, behavior, and ownership." coverCaption="NMIT’s incremental-modernization design replaces selected capabilities while useful legacy functions remain. The modular building is a conceptual illustration, not a customer architecture.">
    <div className="article-introduction"><p>Incremental legacy modernization applies the Strangler Fig pattern by replacing selected capabilities gradually, routing each migrated operation to its new implementation while the legacy system continues to serve the rest.</p><p>The pattern needs more than a new API in front of old code. You must identify meaningful boundaries, preserve contract behavior, control write authority, and establish evidence that each replacement can operate independently.</p><p>This guide develops a hypothetical customer-profile replacement with routing, data, release, and retirement decisions. It describes proposals to validate, not a deployed NMIT case study. If your goal is to keep existing applications connected rather than replace their functions, start with <Link to="/blog/legacy-system-integration">our legacy system integration guide</Link>.</p></div>
    <Section id="strangler-fit" title="Use the pattern when coexistence and controlled interception are feasible">
      <p><Source href="https://martinfowler.com/bliki/StranglerFigApplication.html">Martin Fowler’s Strangler Fig explanation</Source> describes gradual replacement. <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/strangler-fig">Microsoft’s pattern guidance</Source> describes a façade that routes work between retained and new implementations. The business-facing interface can remain stable while responsibility moves behind it.</p><p>Assess interception and internal dependencies before choosing this approach. A vendor-controlled application may not let you redirect its internal calls or disable migrated functions. A small replaceable system or a mandatory near-term shutdown can make extended coexistence unsuitable.</p><p><Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/strangler-fig.html">AWS Strangler Fig guidance</Source> discusses incremental decomposition and its considerations. Do not assume every modernization should end in many microservices. A well-bounded replacement can be a module or service whose operating complexity matches the team.</p><p>Record the intended endpoint: selected replacement, full retirement, or long-term coexistence. If the legacy system will remain, define its continuing contract and ownership rather than describing every retained dependency as temporary.</p>
      <Note title="Coexistence creates work">Two implementations, transition adapters, routing policies, and data synchronization need testing and ownership. They can reduce the size of each change while adding temporary operating obligations.</Note>
    </Section>
    <Section id="strangler-slice" title="Choose a capability with a measurable outcome and a defensible boundary">
      <p>Pick a business capability such as viewing an approved customer profile, rather than extracting arbitrary tables or controller files. Identify its consumers, data authority, permissions, transaction boundaries, and dependencies on unmigrated functions.</p>
      <Table caption="Questions for selecting the first modernization slice" headings={['Question','Evidence to gather','Warning sign']} rows={[
        ['Can requests be routed deliberately?','Known consumers, entry points, and internal callers','Uncontrolled paths bypass the intended boundary'],
        ['Is the business contract understood?','Approved examples, permissions, field meanings, side effects','New schema accidentally changes business behavior'],
        ['Can write authority be isolated?','Entity/field owner and source-version rules','Both implementations can change the same value freely'],
        ['Is validation practical?','Representative synthetic cases and baseline outcomes','Only infrastructure health is measured'],
        ['Can the receiver operate it?','Monitoring, recovery, release and escalation owners','Replacement depends on the original developer'],
      ]} />
      <p>Map infrequent jobs, reports, and partner calls too. The <Link to="/blog/hybrid-cloud-migration-checklist#dependency-inventory">hybrid dependency checklist</Link> helps expose paths that normal web traffic misses. Record what discovery observed and which paths still need owner confirmation.</p><p>Prioritize a slice whose value and risk are clear. Choosing the least used screen can make a pilot easy without providing evidence about the difficult dependencies that govern later work. Choosing the largest financial write first can make recovery unnecessarily complex.</p>
    </Section>
    <Section id="strangler-routing" title="Make routing an explicit, versioned operating decision">
      <p>Define which capability, consumer, or approved cohort uses the replacement. Keep policy reviewable and observable. A route change must preserve authentication, object-level authorisation, required headers, and error semantics.</p><p><Source href="https://spec.openapis.org/oas/latest.html">OpenAPI</Source> can describe the HTTP contract. Compare meaningful behavior as well as payload shape: missing fields, explicit clears, pagination, identity scope, and the stage represented by a success response.</p><p>When semantics differ, use a focused translation boundary. <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer">Microsoft’s anti-corruption-layer pattern</Source> describes protecting one model from another’s conventions. Decide whether that adapter is transitional or an ongoing integration responsibility.</p><p>Monitor the router itself for availability, latency, and policy failures. It can become a bottleneck. Retained functions must still work when a replacement is unavailable; define the permitted fallback without assuming all writes can be sent back safely.</p>
      <ContentImage article="incremental-legacy-modernization" name="routing-boundary" alt="NMIT engineers route a selected request through one controlled boundary to either a legacy folder or a new capability folder." caption="The illustration shows responsibility selection, not sending one business write to both implementations. NMIT’s routing policy needs contract, security, and recovery evidence." />
    </Section>
    <Section id="strangler-data" title="Separate implementation routing from data authority">
      <p>A request reaching the new service does not automatically make its database authoritative. Document where each entity and field is read and written during every transition stage. Preserve stable identity and track versions within their source scope.</p><p>For a read-only replacement, an approved replicated view can be useful if freshness and access rules fit the business. For a writer transition, plan the initial load, catch-up boundary, in-flight work, and the point at which the old writer is fenced.</p><p>Avoid uncontrolled dual writes. One system can succeed while the other fails, producing divergent records. Where you control the source transaction, the <Source href="https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html">transactional outbox pattern</Source> can persist a change and outgoing message together. The relay and consumer still need duplicate-safe effects.</p><p><Source href="https://www.asyncapi.com/docs/concepts/asyncapi-document">AsyncAPI</Source> can describe event contracts. Define event identity, schema version, source meaning, retention, and replay permissions separately. A published event is not proof every consumer has applied it.</p><p>Use <Link to="/blog/erp-crm-integration#conflicting-records">our conflicting-record guidance</Link> for authority and stale updates, and <Link to="/blog/api-vs-event-driven-vs-batch-integration">our pattern comparison</Link> for freshness and coupling tradeoffs.</p>
    </Section>
    <Section id="strangler-example" title="Worked example: replace the customer-profile read before its writer">
      <p>Imagine a fictional legacy portal where profile reads and billing changes share an old application. The initial replacement provides an approved customer-summary read. Finance remains authoritative for billing fields. This is one possible slice, not a prescription for every application.</p><ol><li><strong>Document the read contract:</strong> identity scope, fields, permissions, freshness, and missing-record behavior.</li><li><strong>Build the replacement:</strong> use the agreed source interface or replicated view, keeping source identity and freshness visible.</li><li><strong>Compare safe reads:</strong> evaluate representative outputs without exposing production personal data or invoking write side effects.</li><li><strong>Route a controlled group:</strong> observe contract equivalence, end-to-end response, stale-data behavior, and fallback limits.</li><li><strong>Expand the read boundary:</strong> move confirmed consumers while retaining unmigrated writers and documenting their connections.</li><li><strong>Plan a later writer move:</strong> treat write authority, data transfer, fencing, and correction as a separate release decision.</li></ol>
      <p>Do not use shadow writes to compare implementations by creating real duplicate effects. Read comparison also needs privacy, capacity, and partner approval considerations. A new response containing more fields can be a security regression even if it is faster.</p><p><Source href="https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/">OWASP’s object-level authorisation guidance</Source> supports checking each resource access. Preserve those checks on both routes rather than relying on the façade’s existence.</p>
    </Section>
    <Section id="strangler-release" title="Validate behavior and recovery before expanding responsibility">
      <p>Keep a contract test suite for retained and replacement behavior. Exercise invalid identity, stale data, unavailable dependencies, concurrency, and version conflicts. For financial capabilities, use the cases in <Link to="/blog/payment-api-testing-checklist">our payment failure-testing checklist</Link>.</p><p><Source href="https://learn.microsoft.com/en-us/azure/well-architected/operational-excellence/safe-deployments">Microsoft’s safe-deployment guidance</Source> supports controlled rollout and health evaluation. <Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/reliability-test">Its reliability-testing guidance</Source> covers fault and recovery validation. Set workload-specific stop conditions before release.</p><p>Keep route identity in bounded telemetry dimensions and business operation records. The <Source href="https://www.w3.org/TR/trace-context/">W3C Trace Context standard</Source> helps correlate instrumented requests; sampled traces do not replace durable evidence.</p><p>Routing back after a read replacement can differ substantially from returning a writer. Once the replacement accepts writes, the legacy store may be stale or lack compatible semantics. A valid rollback needs reconciled state and accounting for external effects, not just the prior route configuration.</p><p>Review complete business outcomes with <Link to="/blog/api-integration-monitoring">our integration monitoring guide</Link>. <Source href="https://sre.google/sre-book/monitoring-distributed-systems/">Google’s monitoring chapter</Source> adds diagnostic context, but a technically healthy router cannot establish a correct customer record.</p>
    </Section>
    <Section id="strangler-retire" title="Retire a legacy capability only after its dependencies are resolved">
      <ul className="article-checklist"><li>All intended consumers and internal callers use the approved replacement path.</li><li>Scheduled jobs, reports, partner callbacks, and recovery paths were reviewed.</li><li>Data authority, history retention, and correction responsibility are agreed.</li><li>Replacement behavior and recovery were validated against the accepted contract.</li><li>New writes and external side effects are accounted for in recovery procedures.</li><li>Receiving-team documentation, access, and escalation are accepted.</li><li>Removal of code, data objects, routes, and credentials follows approved retention and change processes.</li></ul>
      <ContentImage article="incremental-legacy-modernization" name="retirement-gate" alt="NMIT engineers review an old module and its remaining dependency before retiring it beside a validated replacement capability." caption="Retirement is a separate gate. The remaining dependency tag represents work to resolve, not a reason to delete the legacy module because the new endpoint is responding." />
      <p>A retained façade may still serve older clients; define its owner and lifecycle. Removing legacy tables too early can make recovery significantly harder. Preserve the evidence behind each retirement decision and keep known retained dependencies visible.</p>
    </Section>
    <Section id="strangler-operations" title="Budget the transition and hand over both routes">
      <p>Include coexistence environments, adapters, routing, contract tests, reconciliation, instrumentation, and recovery drills in the <Link to="/blog/api-integration-project-cost">project-cost scope</Link>. Temporary infrastructure is still infrastructure that somebody must operate.</p><p>Use the <Link to="/blog/integration-handover-checklist">integration handover checklist</Link> before responsibility expands. The receiving team needs to explain which implementation and data owner served an operation, and what can safely happen if it fails.</p><p>Discuss one capability and its dependencies through <Link to="/services">NMIT’s API integration and cloud services</Link> or an <Link to="/contact/workshop">integration-modernization workshop enquiry</Link>. Define the boundary before choosing the number of services.</p>
    </Section>
    <Section id="strangler-faq" title="Common questions about the Strangler Fig pattern">
      <h3>Does incremental modernization require microservices?</h3><p>No. The essential mechanism is gradual capability replacement behind controlled boundaries. Choose an implementation structure the team can operate.</p>
      <h3>Can both implementations write the same record?</h3><p>Only through an explicitly designed authority and consistency mechanism. Uncontrolled dual writes can diverge after partial failures.</p>
      <h3>When can the legacy function be removed?</h3><p>After its consumers, data, recovery paths, and operating responsibility are accounted for and accepted. A responding replacement endpoint alone is insufficient evidence.</p>
    </Section>
  </ArticleGuide>;
}
