import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['test-invariants', 'Define what must remain true'], ['test-environments', 'Separate simulation from provider evidence'], ['duplicate-tests', 'Test duplicates and concurrency'], ['lost-response-tests', 'Lose the response after acceptance'], ['outage-tests', 'Test partner outages and recovery'], ['callback-tests', 'Validate callbacks and ordering'], ['financial-tests', 'Check reconciliation and security'], ['test-evidence', 'Keep a repeatable evidence record'], ['release-gate', 'Set the release gate'], ['testing-faq', 'Common questions']] as const;

export function PaymentApiTesting() {
  return <ArticleGuide slug="payment-api-testing-checklist" category="Payment testing" minutes={10} contents={contents} deck="Test what happens after the happy path breaks: repeated requests, accepted payments with missing responses, delayed callbacks, and a partner that stays unavailable." coverCaption="NMIT’s payment-testing approach checks failure behavior against explicit business outcomes. The checklist and duplicate tickets are conceptual illustrations, not proof of a completed customer test.">
    <div className="article-introduction"><p>A payment API testing checklist should verify financial correctness as well as successful requests. Test duplicate submissions, lost responses, partner outages, callback failures, and reconciliation before treating an integration as ready for release.</p><p>The central question is whether the application can explain one payment intent after a partial failure. A green HTTP response, a passing unit test, or a provider sandbox screenshot does not by itself establish that the order, provider record, and ledger agree.</p><p>This guide turns the recovery design in <Link to="/blog/partner-payment-apis">our payment API integration article</Link> into test scenarios and pass criteria. Examples are hypothetical. Choose the exact cases from your payment methods, endpoint contracts, and fulfilment rules; do not assume all providers offer the same duplicate-prevention or status-retrieval capabilities.</p></div>

    <Section id="test-invariants" title="Write the business invariants before the test cases">
      <p>An invariant is a condition that must hold through retries, crashes, and recovery. Start with the payment operation, then identify the local effects it can cause: an invoice entry, order dispatch, account activation, refund, or partner credit.</p>
      <ul><li>One authorised business intent must not create an unintended second provider operation.</li><li>A missing response remains an unknown outcome until authoritative evidence resolves it.</li><li>The selected payment stage permits fulfilment only once, even if several workers see confirmation.</li><li>Callbacks cannot expose another customer’s payment or bypass valid lifecycle transitions.</li><li>Every unmatched financial record has a retained exception and an assigned owner.</li></ul>
      <p>Define authorisation, capture, refund, and settlement separately where the method distinguishes them. The test oracle is the expected state of independent records, not merely the status returned by the component under test. Our <Link to="/blog/legacy-system-integration#failure-handling">legacy-integration failure-handling guide</Link> explains why remote writes and local responses can diverge.</p><p>Write forbidden outcomes too: a second charge after a timeout, a delivered order with no required confirmation, or a failed reconciliation row silently discarded. These make an apparently successful recovery easier to challenge.</p>
    </Section>

    <Section id="test-environments" title="Use three evidence layers: local simulation, provider sandbox, and release configuration">
      <p>Local tests can deterministically create response loss, process crashes, and concurrency. A provider sandbox checks supported request shapes and payment scenarios. Release-configuration review checks that credentials, callback destinations, permissions, and alert routing belong to the intended environment.</p><p><Source href="https://docs.stripe.com/testing">Stripe’s testing documentation</Source> provides simulated payment values and warns against load testing its testing environments. <Source href="https://developer.paypal.com/sandbox-testing/overview">PayPal’s sandbox guide</Source> and <Source href="https://docs.adyen.com/development-resources/testing/">Adyen’s integration testing guide</Source> describe their own facilities. A simulated bank outcome is not a measurement of live network behavior.</p>
      <Table caption="Keep each test result within the capability it actually exercised" headings={['Evidence layer', 'What to verify', 'What it cannot establish alone']} rows={[
        ['Local harness', 'State transitions, race conditions, crash recovery, UI messaging', 'The provider really implements the assumed contract'],
        ['Provider sandbox', 'Supported payloads, method scenarios, callback format, documented replay', 'Live bank timing, real settlement, or production outage behavior'],
        ['Release review', 'Correct environment, permission scope, routing, monitoring and runbooks', 'A successful real financial end-to-end outcome'],
      ]} />
      <p>Use synthetic customer identifiers and provider-approved test methods. Keep environments separate, including signing secrets and queues. Name the API version, SDK version, payment method, merchant scope, and test configuration in the evidence record. Repeat relevant tests when any of those change.</p>
    </Section>

    <Section id="duplicate-tests" title="Test repeated requests, concurrent workers, and duplicate business effects">
      <p>Duplicate prevention needs more than a repeated request from one browser. Exercise two workers claiming the same intent, two callbacks arriving together, and a worker restarting after a remote operation succeeded but before the local result was committed.</p><p><Source href="https://docs.stripe.com/api/idempotent_requests">Stripe’s idempotency reference</Source> specifies saved responses and parameter checks. <Source href="https://developer.paypal.com/api/rest/reference/idempotency/">PayPal’s idempotency guidance</Source> makes support API-specific. Verify the endpoint’s scope and retention before assigning a replay expectation.</p>
      <Table caption="Duplicate scenarios and observable pass criteria" headings={['Scenario', 'Inject', 'Pass evidence']} rows={[
        ['Double submission', 'Submit the same active order intent from two clients', 'One claimed intent; no unintended second provider operation'],
        ['Same-key replay', 'Replay the unchanged request using its original supported key', 'Provider behavior matches its contract; one guarded local effect'],
        ['Changed payload', 'Reuse a key with a different amount or currency', 'Documented rejection or controlled handling; no silent changed intent'],
        ['Concurrent workers', 'Pause both workers before claiming or applying confirmation', 'Atomic claim/effect guard survives the race'],
        ['Expired external key', 'Simulate replay beyond documented retention', 'Internal duplicate guard prevents unsafe blind resubmission'],
      ]} />
      <p>Count business effects directly. Two event receipts in the inbox can be legitimate; two dispatches for one confirmed order are not. If a remote effect cannot participate in your local transaction, test its separate operation key or outcome-resolution path. An in-memory flag that disappears on restart is insufficient evidence.</p>
      <ContentImage article="payment-api-testing-checklist" name="duplicate-effects" alt="NMIT engineers inspect two copies of payment event E1 while allowing one guarded order fulfilment effect." caption="Duplicate delivery and duplicate business effects are separate concerns. NMIT’s tests inspect the durable record and the resulting order action, not just the callback response." />
    </Section>

    <Section id="lost-response-tests" title="Worked test: accept the payment, lose the response, and restart the worker">
      <p>Use fictional operation <code>TEST-PAY-208</code> and a mock provider configured to accept one request. The harness must drop the response after acceptance; failing before dispatch tests a different condition. Keep that distinction explicit in the test name.</p>
      <ol><li>Persist the operation, amount, currency, fingerprint, and original key before dispatch.</li><li>Let the mock create a provider resource. Drop its response and allow the caller deadline to expire.</li><li>Assert that the customer sees confirmation pending, the order remains unfulfilled, and the original intent is retained.</li><li>Restart the recovery worker. Resolve through a supported status lookup or safe original-key replay; never assume the missing response means no payment exists.</li><li>Deliver confirmation while a second recovery worker runs. Assert one valid state transition and one fulfilment effect.</li><li>Compare the final operation, mock-provider resource, order, and ledger. Retain the trace of how uncertainty was resolved.</li></ol>
      <p>Run a second branch where the mock never accepted the operation, and a third where authoritative status remains unavailable. The third should reach the documented investigation path rather than invent success or failure. <Source href="https://docs.stripe.com/error-low-level">Stripe’s advanced error handling</Source> explains why some server errors leave outcomes indeterminate.</p>
      <ContentImage article="payment-api-testing-checklist" name="fault-injection" alt="NMIT engineers disconnect a response cable in an isolated payment test and record an unknown outcome beside a mock acceptance receipt." caption="Inject the fault at the intended boundary. This scene represents an isolated simulation; an accepted request with a lost response exercises a different recovery path from a request never sent." />
    </Section>

    <Section id="outage-tests" title="Keep the partner unavailable long enough to exercise escalation">
      <p>Test slow responses, intermittent failures, throttling, and sustained unavailability separately. Include the combined effect of SDK retries and application retries. Record outgoing attempts so a retry storm cannot hide behind a single application request.</p><p>Assert connection and total deadlines, bounded attempts, delayed retry scheduling, and an overall resolution deadline. Where a valid instruction is returned, check handling of <Source href="https://www.rfc-editor.org/rfc/rfc9110.html#name-retry-after">HTTP Retry-After</Source>. <Source href="https://docs.adyen.com/development-resources/api-idempotency/">Adyen’s API idempotency documentation</Source> also specifies endpoint recovery signals; use provider-specific expectations.</p><p>A <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker">circuit breaker</Source> should reduce new calls to an unhealthy dependency. Test its opening, limited recovery probes, and reopening if the partner fails again. Opening the circuit must not erase unknown operations already sent.</p><p>When the partner returns, verify controlled backlog recovery within downstream quotas. New work and old unknowns need a scheduling policy. Check that escalation reaches the right team and includes safe correlation references. <Source href="https://learn.microsoft.com/en-us/azure/well-architected/reliability/reliability-test">Microsoft’s reliability-testing guidance</Source> supports testing dependency failures and recovery across complete flows.</p>
    </Section>

    <Section id="callback-tests" title="Replay callbacks, reverse their order, and fail durable acceptance">
      <p>Test invalid signatures, altered payloads, the same event twice, different events for the same payment, and a valid older notification delivered after a newer state. <Source href="https://docs.stripe.com/webhooks">Stripe’s webhook documentation</Source> describes signature verification, duplicate events, and delivery without guaranteed order.</p><p>Fail the inbox database before durable acceptance. The endpoint must not acknowledge successful acceptance of a record it cannot recover. Then crash the processor after acceptance and verify restart from the durable inbox. Test the separate window between applying a business effect and recording completion.</p><p>Out-of-order handling must respect the provider lifecycle, with an authoritative re-read where needed. A refund after capture is not a regression to unpaid; a stale processing event must not overwrite confirmed capture. Our <Link to="/blog/api-vs-event-driven-vs-batch-integration#ordering-recovery">integration-pattern ordering guide</Link> gives the broader design context.</p>
    </Section>

    <Section id="financial-tests" title="Reconcile mismatches and test access boundaries">
      <p>Feed the matching job a duplicate report, missing operation, amount mismatch, partial refund, and separate-currency totals. Verify exception identity, ageing, assignment, and approved corrections. <Source href="https://docs.stripe.com/reports/balance-transaction-types">Stripe’s balance-transaction reference</Source> distinguishes financial categories that must not be collapsed into one paid flag.</p><p>Use the independent checks in <Link to="/blog/partner-payment-apis#reconciliation">our reconciliation guide</Link>. If the payment result updates customer records, test a failed downstream sync without creating the charge again; see <Link to="/blog/erp-crm-integration#failed-syncs">ERP–CRM failed-record recovery</Link>.</p><p>Attempt payment-status access from another customer or merchant scope. Test restricted operator permissions and log redaction. <Source href="https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/">OWASP’s object-level authorisation guidance</Source> describes why an identifier alone is not permission. Never put credentials or raw payment details into the test report.</p>
    </Section>

    <Section id="test-evidence" title="Keep evidence another engineer can reproduce">
      <p>For each case, retain its ID, invariant, setup, injection point, expected outcome, actual result, relevant versions, and redacted record references. Distinguish a simulated guarantee from a provider-verified capability. Include the reason for skipped tests and the owner of the resulting limitation.</p><p><Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry’s signals overview</Source> separates traces, metrics, and logs. Correlate them with the test operation: attempts and state transitions in logs, timing across boundaries in traces, and unknown-age or backlog measures in metrics.</p><p>Keep a deterministic local suite for common faults and a smaller provider-contract suite. Add regression cases after incidents. Carry the test environment, partner coordination, and evidence handover into the estimate using <Link to="/blog/api-integration-project-cost">our API integration project cost guide</Link>.</p>
    </Section>

    <Section id="release-gate" title="Approve release against outcomes, owners, and unresolved limits">
      <ul className="article-checklist"><li>Critical duplicate, unknown-outcome, and crash scenarios have reproducible results.</li><li>The tested provider contract, payment method, and SDK configuration match the proposed release.</li><li>Callbacks and reconciliation recover retained work without duplicate effects.</li><li>Customer messages distinguish pending confirmation from a verified failure.</li><li>Alerts, exception ownership, escalation, and replay permissions have been exercised.</li><li>Any untested live behavior is recorded with an accountable acceptance decision.</li></ul><p>Document the release configuration separately from sandbox evidence. Use a provider-approved launch process rather than improvising live financial tests. Discuss test and operational ownership through <Link to="/services">NMIT’s API integration and DevOps services</Link> or bring the unresolved failure cases to an <Link to="/contact/workshop">integration workshop</Link>.</p>
    </Section>

    <Section id="testing-faq" title="Common questions about payment API testing">
      <h3>Is a successful sandbox payment enough?</h3><p>No. It verifies one supported path. Add controlled response loss, concurrency, callback recovery, reconciliation, and release-configuration checks.</p>
      <h3>How do we test an unknown outcome?</h3><p>Accept a mock operation, suppress its response after acceptance, and observe pending state and safe resolution. Separately test a request that was never accepted.</p>
      <h3>Can we load test against a provider sandbox?</h3><p>Only according to the provider’s rules. Stripe directs load testing away from its testing environments. Use an appropriate local model for capacity tests and label the limits of that evidence.</p>
    </Section>
  </ArticleGuide>;
}
