import { Link } from 'react-router-dom';
import { ArticleGuide, ContentImage, Note, Section, Source, Table } from './ArticleGuide';

const contents = [['payment-state', 'Separate request and payment state'], ['timeout-example', 'A timeout, worked through'], ['idempotency', 'Choose stable operation keys'], ['retry-policy', 'Make retries bounded'], ['webhook-processing', 'Process callbacks safely'], ['reconciliation', 'Reconcile three records'], ['payment-security', 'Protect the boundary'], ['payment-checklist', 'Test the failure paths'], ['payment-faq', 'Common questions']] as const;

export function PaymentApiIntegration() {
  return <ArticleGuide slug="partner-payment-apis" category="Payment reliability" minutes={11} contents={contents} deck="A lost response is not proof of a failed payment. Keep uncertainty visible, prevent duplicate operations, and reconcile against independent evidence." coverCaption="NMIT’s payment-integration work connects request handling, confirmation, and reconciliation. This conceptual cover shows those responsibilities; a timeout can remain unresolved rather than progressing to success.">
    <div className="article-introduction"><p>Payment API integration connects a business application with a payment provider while maintaining a trustworthy record of what was requested, what the provider confirmed, and what eventually settled. Handling timeouts, retries, and reconciliation is central to that record.</p><p>When a payment request times out, the caller knows it did not receive a complete response. It may not know whether the provider received, processed, or completed the operation. Treating that uncertainty as a decline can lead to a second charge; treating it as success can trigger premature fulfilment.</p><p>This guide expands our partner-payment article with a hypothetical order, a recovery policy, and a reconciliation process. For the wider system boundaries, begin with <Link to="/blog/legacy-system-integration">connecting legacy ERP, CRM, and partner systems</Link>. The states below are an application model, not a replacement for any provider’s documented lifecycle.</p></div>

    <Section id="payment-state" title="Keep transport state separate from payment state">
      <p>A successful HTTP exchange and a successful financial operation are different facts. An accepted request may still require customer action, asynchronous processing, or later capture. Similarly, a network exception does not establish that no money moved.</p><p><Source href="https://docs.stripe.com/payments/paymentintents/lifecycle">Stripe’s PaymentIntent lifecycle</Source> illustrates why an integration needs more than a paid/unpaid flag. Map provider-specific statuses into your application explicitly, preserving the original status and resource ID for investigation.</p>
      <Table caption="An illustrative application state model" headings={['Local state', 'Evidence', 'Next action']} rows={[
        ['Prepared', 'Durable intent exists; provider request not yet dispatched', 'Validate inputs, persist an operation key, dispatch once'],
        ['Unknown', 'Response missing or outcome indeterminate', 'Resolve with documented status lookup, safe retry, or investigation'],
        ['Processing / action required', 'Provider confirms an intermediate state', 'Wait or guide the customer through the required action'],
        ['Confirmed failed', 'Authoritative provider evidence of failure', 'Show a justified failure; apply a new-attempt policy'],
        ['Confirmed succeeded', 'Provider confirms the required payment stage', 'Apply the business effect once; continue settlement checks'],
        ['Reconciliation exception', 'Internal and external records disagree', 'Assign an owner and investigate the specific mismatch'],
      ]} />
      <p>Record authorisation, capture, refund, and settlement separately when your payment method distinguishes them. A captured charge can later be refunded or disputed; those are additional operations and ledger entries, not a reason to erase the original evidence. Agree which stage permits dispatch, account activation, or partner credit.</p>
    </Section>

    <Section id="timeout-example" title="Worked example: the provider accepted the payment, but the response was lost">
      <p>Imagine order <code>ORD-1042</code> for INR 1,250.00. The amount is fictional. The provider in this example supports idempotent creation with a retained operation key and a resource-status endpoint. Check those capabilities before adopting this recovery path.</p>
      <ol><li><strong>Before dispatch:</strong> persist operation <code>PAY-1042-A</code>, amount <code>125000</code> paise, currency <code>INR</code>, request fingerprint, and a random idempotency key. A database uniqueness rule prevents two workers from claiming the same charge intent.</li><li><strong>The request leaves:</strong> the provider creates payment resource <code>P-778</code>. The response is lost between the provider and your application. Your client’s illustrative five-second deadline expires.</li><li><strong>The application records Unknown:</strong> keep the original key and payload. Show “Payment confirmation pending” and prevent a second submission for the same active intent. Do not mark the order paid or tell the customer the payment definitely failed.</li><li><strong>A recovery worker resolves it:</strong> if the resource ID is known, query its status. If it is not known and the provider documents safe replay for this failure, retry the same operation with the same key and unchanged parameters within the supported retention window.</li><li><strong>Confirmation arrives:</strong> the replay returns <code>P-778</code>, or an authenticated callback identifies it. A conditional state transition and a unique business-effect key ensure the order is fulfilled once.</li><li><strong>Finance verifies later:</strong> compare the provider’s records with the payment operation and the internal ledger. A later refund or settlement adjustment has its own evidence and accounting treatment.</li></ol>
      <ContentImage article="payment-api-integration" name="timeout-recovery" alt="NMIT engineers compare an unconfirmed order with an accepted provider receipt after a payment API response is lost." caption="A lost response leaves the application uncertain even when the provider has accepted the payment. NMIT’s recovery design preserves the original operation and resolves it using evidence." />
      <p>If the provider supports neither reliable status retrieval nor safe duplicate prevention, stop automatic replay after an ambiguous write. Route the operation to an investigation queue with the provider reference, timestamps, and request ID. Asking the customer to click Pay again is not a recovery strategy.</p><p>The same partial-failure reasoning appears in our <Link to="/blog/legacy-system-integration#failure-handling">legacy-integration failure-handling guide</Link>. It applies whenever a remote side effect can outlive the caller’s response window.</p>
    </Section>

    <Section id="idempotency" title="Make the key identify one business operation">
      <p>An idempotency key lets a provider recognise a repeated operation according to its own contract. Persist it before sending the request. Scope it to the merchant account and operation type; capture, refund, and charge creation must not accidentally share one intent.</p><p><Source href="https://docs.stripe.com/api/idempotent_requests">Stripe’s idempotent-request reference</Source> documents saved responses, parameter matching, and key pruning after at least 24 hours. That window is Stripe-specific. Your internal duplicate guard should cover your own business replay window even after an external key expires.</p><p><Source href="https://developer.paypal.com/api/rest/reference/idempotency/">PayPal’s idempotency guidance</Source> uses <code>PayPal-Request-Id</code>, with support and retention determined by the API. <Source href="https://docs.adyen.com/development-resources/api-idempotency/">Adyen’s idempotency reference</Source> also describes provider-specific retry signals. Write a capability matrix for each endpoint instead of assuming one payment-provider abstraction gives them identical guarantees.</p><p>Use a new key only for a genuinely new operation. A changed amount requires a controlled new attempt after the earlier intent is resolved or safely cancelled. Store the request fingerprint, attempt count, last outcome, and resource reference so an operator can explain why a replay is safe.</p>
      <Note title="The database still has a job">Provider idempotency does not prevent your application from fulfilling an order twice, adding duplicate ledger entries, or processing the same callback twice. Protect those local effects independently.</Note>
    </Section>

    <Section id="retry-policy" title="Classify the failure before scheduling a retry">
      <p>Define connection, read, and total deadlines. Choose them from measured provider latency and the customer’s acceptable wait, not from an arbitrary long timeout. Account for retry behavior already built into the SDK: an application retry wrapped around SDK retries can multiply requests.</p>
      <Table caption="Recovery decisions depend on endpoint semantics" headings={['Failure', 'Default integration response', 'Condition to verify']} rows={[
        ['Validation or authentication error', 'Correct input or credentials; do not blindly retry', 'Whether the endpoint began execution'],
        ['Read timeout / connection lost after dispatch', 'Mark outcome unknown', 'Status lookup or documented replay with the original key'],
        ['Rate limited', 'Pause; honour documented retry timing', 'Quota scope, retry signal, and operation safety'],
        ['Server error', 'Preserve uncertainty about side effects', 'Provider guidance; a new key may duplicate an operation'],
        ['Confirmed business decline', 'Show the documented result', 'Whether a new customer-authorised attempt is appropriate'],
      ]} />
      <p><Source href="https://docs.stripe.com/error-low-level">Stripe’s advanced error handling</Source> treats certain server errors as indeterminate and warns against retrying with a new key. A repeated cached error is not evidence that the original request had no side effects. Follow the endpoint’s documented recovery behavior.</p><p>A proposed background policy might use capped exponential delay with jitter, a maximum attempt count, and an overall resolution deadline. These are design parameters to test. Stop automatic retries when safety cannot be established, and escalate overdue unknowns rather than deleting them.</p><p><Source href="https://www.rfc-editor.org/rfc/rfc9110.html#name-retry-after">HTTP’s Retry-After definition</Source> explains the header’s timing formats. Do not retry earlier than a valid provider instruction. A <Source href="https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker">circuit breaker</Source> can reduce calls to an unhealthy dependency, but opening it does not resolve operations already sent.</p>
    </Section>

    <Section id="webhook-processing" title="Treat callbacks as evidence that needs validation">
      <p>Verify the provider’s signature using the required original payload and secret. Persist the accepted event durably before acknowledging delivery, then process it asynchronously. If durable acceptance fails, return an appropriate failure so the sender can follow its delivery policy.</p><p><Source href="https://docs.stripe.com/webhooks">Stripe’s webhook documentation</Source> covers signature verification, duplicate events, and delivery without guaranteed order. Deduplicate by the documented event identity, then separately guard business effects: multiple different events can refer to one payment.</p><p>A late processing notification must not overwrite a later confirmed capture. Apply valid lifecycle transitions; retrieve the current provider resource when event order leaves the state unclear. Keep refunds and disputes distinct from the charge’s success state. This is a useful application of the <Link to="/blog/api-vs-event-driven-vs-batch-integration">API and event-driven integration tradeoffs</Link>.</p>
    </Section>

    <Section id="reconciliation" title="Reconcile the operation, the provider record, and the ledger">
      <p>Reconciliation checks whether independent records describe the same financial activity. Confirmation of one charge does not prove that fees, refunds, settlement, and bank deposits all match. Build an exception process alongside the matching job.</p><p>Match by merchant account, provider resource ID, internal operation ID, amount, and currency. Retain the original transaction date and the report’s settlement date or timezone. Avoid floating-point arithmetic for monetary comparisons; use the provider’s currency-unit rules and separate currencies in totals.</p><p><Source href="https://docs.stripe.com/reports/balance-transaction-types">Stripe’s balance transaction types</Source> distinguish categories such as charges, refunds, fees, and adjustments. <Source href="https://docs.stripe.com/bank-reconciliation">Stripe’s bank reconciliation documentation</Source> describes reconciling cash movements with bank statements. Choose reports and reconciliation boundaries available to your own account and provider.</p>
      <ul><li><strong>Missing internal record:</strong> investigate an external payment with no matching operation; do not silently insert a guessed order association.</li><li><strong>Missing external record:</strong> distinguish reporting delay from an incorrectly confirmed local payment.</li><li><strong>Amount or currency mismatch:</strong> compare the original intent, capture, partial refund, fee treatment, and exchange-rate handling.</li><li><strong>Duplicate effect:</strong> check whether duplicate ledger entries represent one charge or two separate provider operations.</li></ul>
      <p>Set an owner, ageing threshold, and correction approval for every exception category. Re-running a report should update the same exception, not create a new unresolved ticket each day. Preserve a correction history; never erase evidence to force totals to match.</p><p>When payment results feed customer records, our <Link to="/blog/erp-crm-integration">ERP–CRM synchronization guide</Link> explains field ownership and failed updates. Finance retains authority for the financial record even when the CRM displays its status.</p>
      <ContentImage article="payment-api-integration" name="reconciliation" alt="NMIT engineers reconcile order, payment-provider, and ledger records, setting an unmatched transaction aside for investigation." caption="Reconciliation compares independent records. NMIT’s integration design keeps unmatched items visible for an assigned finance review rather than forcing totals to agree." />
    </Section>

    <Section id="payment-security" title="Protect credentials and make investigation possible">
      <p>Keep payment credentials on the server, restrict permission by operation, and redact sensitive payloads from logs. Verify object-level access before exposing a payment status to a user. <Source href="https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/">OWASP’s object-level authorisation guidance</Source> describes the access checks that resource identifiers require.</p><p>Log correlation IDs, attempt timing, classified error, and state transitions without storing raw card data or secrets. Track the oldest unknown payment, callback-processing delay, retry volume, and reconciliation exceptions. <Source href="https://opentelemetry.io/docs/concepts/signals/">OpenTelemetry’s signals overview</Source> separates traces, metrics, and logs; connect those signals using the business operation reference.</p><p>These operating responsibilities should be part of the delivery scope. <Link to="/services">NMIT’s integration and DevOps services</Link> cover the application boundary and its production ownership.</p>
    </Section>

    <Section id="payment-checklist" title="Test the paths that ordinary happy-path demos miss">
      <ul className="article-checklist"><li>Lose the response after a simulated provider acceptance. Verify Unknown, stable keys, and no duplicate fulfilment.</li><li>Crash the worker before dispatch and after dispatch. Recover from durable intent without guessing whether the request left.</li><li>Deliver duplicate callbacks and callbacks in reverse order. Verify valid state transitions and one local effect.</li><li>Return throttling and prolonged server errors. Check retry caps, escalation, and customer messaging.</li><li>Re-run the same settlement file, omit a record, and introduce a partial refund. Check exception deduplication and accounting ownership.</li><li>Attempt status access from another customer account. Confirm authorisation and log redaction.</li></ul><p>For scenario setup and observable pass criteria, use our <Link to="/blog/payment-api-testing-checklist">payment API testing checklist</Link>.</p><p>Use sandbox facilities and fault injection before a controlled production pilot. Document which provider guarantees were verified and which behaviors were only simulated. Bring unresolved recovery questions to an <Link to="/contact/workshop">integration workshop with NMIT</Link>.</p>
    </Section>

    <Section id="payment-faq" title="Common questions about payment API integration">
      <h3>Should every timed-out payment be retried?</h3><p>No. Retry a write only when the provider’s duplicate-prevention and failure semantics make replay safe. Otherwise resolve its status or investigate it. A timeout alone is not a decline.</p>
      <h3>Does an idempotency key guarantee exactly-once payment handling?</h3><p>It addresses repeated provider requests within a documented scope and retention window. Your state store, ledger, callback worker, and fulfilment process still need their own duplicate protection.</p>
      <h3>Can webhooks replace reconciliation?</h3><p>No. Webhooks help update operational state. Reconciliation compares independent financial records and catches missing entries, fees, settlement differences, and adjustments.</p>
    </Section>
  </ArticleGuide>;
}
