import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Character } from './CharacterGuide';
import type { CharacterPose } from './CharacterGuide';

const workflows: { name:string; title:string; problem:string; plan:string[]; evidence:string; pose:CharacterPose; slug:string; label:string }[] = [
  { name:'Payments', title:'A timeout needs an investigation path.', problem:'The partner may have accepted a payment even when its response is lost. Retrying with a new operation can create a second charge.', plan:['Keep a durable operation identity and an explicit unknown state.','Agree safe replay, callback verification, and reconciliation rules.','Test lost responses and concurrent workers before release.'], evidence:'A payment can be traced from submission to confirmed result or an owned exception.', pose:'woman-review', slug:'partner-payment-apis', label:'Explore payment reliability' },
  { name:'Customer data', title:'Two systems need one rule for each field.', problem:'An ERP and CRM can both hold a customer, but their identifiers, update schedules, and responsibilities may differ.', plan:['Agree record identity, field ownership, and mapping rules.','Choose the update frequency each business process needs.','Retain failed records with enough context for correction and controlled replay.'], evidence:'The receiving record has the intended source version, and conflicting updates have a documented owner.', pose:'woman-explain', slug:'erp-crm-integration', label:'Explore ERP–CRM synchronization' },
  { name:'Cloud transition', title:'Moving one workload changes its dependencies.', problem:'Applications can depend on identities, DNS, jobs, and partner connections that stay outside the new cloud environment.', plan:['Map dependencies and validate connectivity across the boundary.','Plan migration waves, data authority, and cutover checkpoints.','Rehearse recovery and hand over access, monitoring, and escalation.'], evidence:'The complete workflow works across the retained and migrated systems, including its recovery path.', pose:'man-runbook', slug:'hybrid-cloud-migration-checklist', label:'Explore migration readiness' },
];
export function WorkflowExplorer() {
  const [selected,setSelected] = useState(0);
  const flow=workflows[selected];
  return <section id="workflow-explorer" className="workflow-explorer"><div className="section-intro"><span className="eyebrow-mono">One workflow, end to end</span><h2>What are you trying to connect?</h2><p>Choose a starting point. The useful design decisions sit between the systems, where records change, partners respond, and failures need an owner.</p></div><div className="workflow-buttons" role="group" aria-label="Choose a workflow">{workflows.map((w,i)=><button key={w.name} type="button" aria-pressed={selected===i} aria-controls="workflow-detail" onClick={()=>setSelected(i)}><span>0{i+1}</span>{w.name}</button>)}</div><div className="workflow-detail" id="workflow-detail"><div key={flow.name} className="workflow-copy"><h3>{flow.title}</h3><p>{flow.problem}</p><ol>{flow.plan.map(step=><li key={step}>{step}</li>)}</ol><div className="workflow-evidence"><span className="eyebrow-mono">Evidence to agree</span><p>{flow.evidence}</p></div><Link to={`/blog/${flow.slug}`}>{flow.label}</Link></div><div className="workflow-character"><Character pose={flow.pose} /><span className="eyebrow-mono">NMIT · connect with a plan</span></div></div></section>;
}
